import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { HOME_COLORS } from '@/features/home/homeModel';
import {
  Platform,
  StyleSheet
} from 'react-native';
export const styles = StyleSheet.create({
  tripsSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 11,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: Colors.white,
    paddingTop: Spacing.sm,
    borderWidth: 1,
    borderColor: HOME_COLORS.softLine,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.12,
        shadowRadius: 20,
      },
      android: {
        elevation: 16,
      },
    }),
  },
  sheetHeader: {
    paddingHorizontal: Spacing.md,
    paddingBottom: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  sheetHeaderCopy: {
    flex: 1,
    flexBasis: 120,
    minHeight: 44,
    justifyContent: 'center',
    minWidth: 120,
    paddingVertical: 2,
  },
  sheetTitle: {
    color: HOME_COLORS.text,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  sheetHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  seeAllButton: {
    minHeight: 44,
    minWidth: 44,
    justifyContent: 'center',
    paddingHorizontal: Spacing.xs,
  },
  seeAllText: {
    color: HOME_COLORS.rustDark,
    fontSize: 12,
    fontWeight: FontWeights.bold,
  },
  sheetModeSwitch: {
    flex: 1,
    flexBasis: 140,
    minWidth: 140,
    flexDirection: 'row',
    gap: 4,
  },
  sheetModeOption: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.xs,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetModeOptionActive: {
    borderBottomColor: Colors.primary,
  },
  sheetModeText: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
    textAlign: 'center',
  },
  sheetModeTextActive: {
    color: HOME_COLORS.rustDark,
    fontWeight: FontWeights.bold,
  },
  sheetToggle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.gray[100],
  },
  tripsHorizontalContent: {
    alignItems: 'flex-start',
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  tripsList: { flexGrow: 0, flexShrink: 0 },
  sheetState: {
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    minHeight: 64,
    padding: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.gray[50],
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  sheetStateText: {
    flex: 1,
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium,
  },
  retryButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '14',
  },
  retryButtonText: {
    color: HOME_COLORS.rustDark,
    fontWeight: FontWeights.bold,
  },
  emptyCard: {
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: BorderRadius.md,
    minHeight: 64,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray[50],
    gap: Spacing.sm,
  },
  emptyText: {
    flex: 1,
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
  }
});
