import { BorderRadius, Colors, CommonStyles, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { HOME_COLORS } from '@/features/home/homeModel';
import {
  StyleSheet
} from 'react-native';
export const styles = StyleSheet.create({
  homeLoaderContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: HOME_COLORS.surface,
    paddingHorizontal: Spacing.xl,
  },
  homeLoaderLogo: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary + '14',
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  homeLoaderLogoText: {
    color: Colors.primary,
    fontSize: FontSizes.xxl,
    fontWeight: FontWeights.bold,
  },
  homeLoaderTitle: {
    color: HOME_COLORS.ink,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    textAlign: 'left',
  },
  homeLoaderText: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    lineHeight: 20,
    textAlign: 'left',
  },
  homeLoaderShell: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 30,
    overflow: 'hidden',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: HOME_COLORS.softLine,
    ...CommonStyles.shadowMd,
  },
  homeLoaderMapPane: {
    height: 190,
    overflow: 'hidden',
    backgroundColor: '#EEF4F3',
  },
  homeLoaderRoad: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: '#D8E4E9',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  homeLoaderRoadVertical: {
    width: 58,
    height: 240,
    left: 42,
    top: -22,
    transform: [{ rotate: '8deg' }],
  },
  homeLoaderRoadDiagonal: {
    width: 52,
    height: 260,
    right: 74,
    top: -36,
    transform: [{ rotate: '-33deg' }],
  },
  homeLoaderRoadSoft: {
    width: 42,
    height: 180,
    right: -8,
    bottom: -18,
    opacity: 0.7,
    transform: [{ rotate: '20deg' }],
  },
  homeLoaderPulseAnchor: {
    position: 'absolute',
    left: 52,
    top: 44,
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeLoaderPulseRing: {
    position: 'absolute',
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: Colors.primary,
  },
  homeLoaderGpsDot: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    borderWidth: 3,
    borderColor: Colors.white,
    ...CommonStyles.shadowSm,
  },
  homeLoaderRouteTrack: {
    position: 'absolute',
    left: 86,
    right: 70,
    bottom: 44,
    height: 54,
    justifyContent: 'center',
  },
  homeLoaderRouteLine: {
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(48,75,119,0.22)',
  },
  homeLoaderRoutePoint: {
    position: 'absolute',
    top: 18,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 4,
    backgroundColor: Colors.white,
  },
  homeLoaderRouteStartPoint: {
    left: -4,
    borderColor: HOME_COLORS.success,
  },
  homeLoaderRouteEndPoint: {
    right: -4,
    borderColor: Colors.primary,
  },
  homeLoaderVehicle: {
    position: 'absolute',
    left: 0,
    top: 7,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    borderWidth: 3,
    borderColor: Colors.white,
    ...CommonStyles.shadowSm,
  },
  homeLoaderCopy: {
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  homeLoaderLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeLoaderTitleBlock: {
    flex: 1,
    minWidth: 0,
    marginLeft: Spacing.md,
  },
  homeLoaderStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  homeLoaderStatusPill: {
    minHeight: 34,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: HOME_COLORS.softLine,
  },
  homeLoaderStatusText: {
    color: HOME_COLORS.ink,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  homeLoaderTripPreview: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: BorderRadius.xl,
    padding: Spacing.md,
    backgroundColor: '#FFFDFC',
    borderWidth: 1,
    borderColor: HOME_COLORS.line,
  },
  homeLoaderShimmer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 74,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  homeLoaderTripTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  homeLoaderAvatarSkeleton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colors.gray[100],
  },
  homeLoaderTripCopy: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  homeLoaderLineStrong: {
    width: '68%',
    height: 12,
    borderRadius: 999,
    backgroundColor: '#DDE5EA',
  },
  homeLoaderLineShort: {
    width: '46%',
    height: 9,
    borderRadius: 999,
    backgroundColor: '#E9EEF2',
  },
  homeLoaderPriceSkeleton: {
    width: 58,
    height: 18,
    borderRadius: 999,
    backgroundColor: Colors.primary + '22',
  },
  homeLoaderRoutePreview: {
    marginTop: Spacing.md,
    flexDirection: 'row',
  },
  homeLoaderRoutePreviewRail: {
    width: 18,
    alignItems: 'center',
    marginRight: Spacing.md,
  },
  homeLoaderMiniDot: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderWidth: 4,
    backgroundColor: Colors.white,
  },
  homeLoaderMiniStart: {
    borderColor: HOME_COLORS.success,
  },
  homeLoaderMiniEnd: {
    borderColor: Colors.primary,
  },
  homeLoaderMiniLine: {
    height: 28,
    borderLeftWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: HOME_COLORS.body,
    marginVertical: 4,
  },
  homeLoaderWideLine: {
    width: '88%',
    height: 13,
    borderRadius: 999,
    backgroundColor: '#DDE5EA',
  },
  homeLoaderMediumLine: {
    width: '62%',
    height: 13,
    borderRadius: 999,
    backgroundColor: '#E9EEF2',
  },
  homeLoaderChipRow: {
    marginTop: Spacing.md,
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  homeLoaderChipSkeleton: {
    width: 92,
    height: 34,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
  },
  homeLoaderChipSkeletonWide: {
    width: 116,
    height: 34,
    borderRadius: BorderRadius.full,
    backgroundColor: HOME_COLORS.navySoft,
  }
});
