import { BorderRadius, Colors, CommonStyles, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { HOME_COLORS } from '@/features/home/homeModel';
import {
  StyleSheet
} from 'react-native';
export const styles = StyleSheet.create({
  requestPreviewCard: {
    minHeight: 208,
    borderRadius: BorderRadius.xl,
    backgroundColor: '#FBFEFF',
    borderWidth: 1,
    borderColor: HOME_COLORS.softLine,
    padding: Spacing.md,
    ...CommonStyles.shadowSm,
  },
  requestPreviewTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  requestPassengerInline: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  requestPreviewAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    marginRight: Spacing.sm,
    backgroundColor: Colors.gray[100],
  },
  requestPreviewAvatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: HOME_COLORS.navySoft,
  },
  requestPreviewAvatarText: {
    color: HOME_COLORS.navy,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  requestPreviewPassengerCopy: {
    flex: 1,
    minWidth: 0,
  },
  requestPreviewPassengerName: {
    color: HOME_COLORS.ink,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  requestPreviewDate: {
    marginTop: 2,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  requestPreviewStatusBadge: {
    flexShrink: 0,
    maxWidth: 132,
    minHeight: 30,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  requestPreviewStatusText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  requestPreviewRoute: {
    flexDirection: 'row',
    marginTop: Spacing.md,
    flexShrink: 1,
  },
  requestPreviewRail: {
    width: 18,
    alignItems: 'center',
    paddingVertical: 3,
    marginRight: Spacing.md,
  },
  requestPreviewRouteDot: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderWidth: 4,
    backgroundColor: Colors.white,
  },
  requestPreviewStartDot: {
    borderColor: HOME_COLORS.success,
  },
  requestPreviewEndDot: {
    borderColor: Colors.primary,
  },
  requestPreviewRouteLine: {
    flex: 1,
    minHeight: 22,
    borderLeftWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: HOME_COLORS.body,
    marginVertical: 3,
  },
  requestPreviewRouteCopy: {
    flex: 1,
    minWidth: 0,
    gap: Spacing.sm,
  },
  requestPreviewRouteLabel: {
    color: HOME_COLORS.body,
    fontSize: 10,
    fontWeight: FontWeights.bold,
  },
  requestPreviewRouteText: {
    marginTop: 2,
    color: HOME_COLORS.text,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  requestPreviewFooter: {
    marginTop: 'auto',
    paddingTop: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  requestPreviewChips: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    overflow: 'hidden',
  },
  requestPreviewChip: {
    flexShrink: 1,
    maxWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: HOME_COLORS.navySoft,
  },
  requestPreviewChipText: {
    color: HOME_COLORS.navy,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  requestPreviewBudgetChip: {
    flexShrink: 1,
    maxWidth: 118,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '14',
  },
  requestPreviewBudgetText: {
    color: Colors.primary,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  requestPreviewOffersChip: {
    flexShrink: 1,
    maxWidth: 96,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: '#DDF8EA',
  },
  requestPreviewOffersText: {
    color: HOME_COLORS.success,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  requestPreviewOpenButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: HOME_COLORS.navy,
  }
});
