import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  directAcceptSecondaryButtonDisabled: {
    borderColor: Colors.gray[300],
    backgroundColor: Colors.gray[50],
  },
  directAcceptSecondaryButtonText: {
    color: Colors.primary,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  directAcceptPrimaryButton: {
    flex: 1.35,
    minHeight: 48,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  directAcceptPrimaryButtonText: {
    flexShrink: 1,
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    textAlign: 'center',
  },
  directAcceptButtonDisabled: {
    backgroundColor: Colors.gray[400],
    opacity: 0.72,
  },
  directAcceptButtonTextDisabled: {
    color: Colors.gray[400],
  },
  ownerProgressPanel: {
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray[50],
  },
  ownerProgressHeader: {
    marginBottom: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  ownerProgressTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  ownerProgressCount: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  driverOverridePanel: {
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[200],
    marginBottom: 0,
    overflow: 'hidden',
  },
  driverOverrideToggle: {
    minHeight: 52,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  driverOverrideTogglePressed: {
    backgroundColor: Colors.gray[100],
  },
  driverOverrideToggleIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverOverrideToggleCopy: {
    flex: 1,
    minWidth: 0,
  },
  driverOverrideTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  driverOverrideSubtitle: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
  },
  driverOverrideFields: {
    gap: Spacing.sm,
    padding: Spacing.md,
    paddingTop: 0,
  },
  driverOverrideButton: {
    minHeight: 42,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: Colors.white,
  },
  driverOverrideButtonText: {
    flex: 1,
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  driverOverrideInput: {
    minHeight: 42,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    paddingHorizontal: Spacing.md,
    color: Colors.gray[900],
    backgroundColor: Colors.white,
  },
  ownerHeroSteps: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  ownerHeroStep: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  ownerHeroStepDot: {
    width: '100%',
    height: 4,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[200],
  },
  ownerHeroStepDotActive: {
    backgroundColor: Colors.primary,
  },
  ownerHeroStepText: {
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
    fontWeight: FontWeights.medium,
  },
  ownerHeroStepTextActive: {
    color: Colors.primaryDark,
    fontWeight: FontWeights.bold,
  },
  ownerHeroPrimaryButton: {
    minHeight: 48,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary,
    borderWidth: 1,
    borderColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  ownerHeroPrimaryButtonText: {
    color: Colors.white,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  ownerHeroHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[100],
  },
  ownerHeroHintText: {
    flex: 1,
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    lineHeight: 18,
  },
  ownerHeroActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  ownerHeroSecondaryActions: {
    marginTop: Spacing.sm,
  },
  ownerHeroGhostButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '22',
    backgroundColor: Colors.primary + '10',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
  },
  ownerHeroGhostButtonDanger: {
    backgroundColor: Colors.danger + '08',
    borderColor: Colors.danger + '24',
  },
  ownerHeroButtonPressed: {
    opacity: 0.72,
  },
  ownerHeroButtonDisabled: {
    opacity: 0.6,
  },
  ownerHeroGhostButtonText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  ownerHeroGhostButtonTextDanger: {
    color: Colors.danger,
  },
  driverHeroPassengerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  driverHeroAvatar: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  driverHeroPassengerInfo: {
    flex: 1,
  },
  driverHeroRoleBadge: {
    minHeight: 28,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  driverHeroRoleBadgeText: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  driverHeroPassengerLabel: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  driverHeroPassengerName: {
    marginTop: 2,
    color: Colors.gray[900],
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  statusCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  statusBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  statusText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  ownerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  }
});
