import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  driverFact: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: Spacing.xs,
    alignItems: 'flex-start',
  },
  driverFactDivider: {
    width: 1,
    marginHorizontal: Spacing.xs,
    backgroundColor: Colors.gray[200],
  },
  driverFactLabel: {
    marginTop: Spacing.xs,
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: FontWeights.semibold,
    textTransform: 'uppercase',
  },
  driverFactValue: {
    marginTop: 3,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    lineHeight: 18,
  },
  ownerPassengerKycNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '30',
    backgroundColor: Colors.primary + '08',
    gap: Spacing.sm,
  },
  ownerPassengerKycNoticeIcon: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  ownerPassengerKycNoticeCopy: {
    flex: 1,
    minWidth: 0,
  },
  ownerPassengerKycNoticeTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  ownerPassengerKycNoticeText: {
    marginTop: 3,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  directVehiclePicker: {
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Colors.gray[200],
  },
  directVehiclePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  directVehiclePickerIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  directVehiclePickerCopy: {
    flex: 1,
    minWidth: 0,
  },
  directVehiclePickerTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  directVehiclePickerSubtitle: {
    marginTop: 2,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 16,
  },
  directVehicleRequired: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
    overflow: 'hidden',
    color: Colors.primaryDark,
    backgroundColor: Colors.primary + '12',
    fontSize: 9,
    fontWeight: FontWeights.bold,
    letterSpacing: 0.5,
  },
  directVehicleList: {
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  directVehicleCard: {
    width: 158,
    minHeight: 96,
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1.5,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  directVehicleCardSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '08',
  },
  directVehicleCardPressed: {
    opacity: 0.78,
  },
  directVehicleCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  directVehicleRadio: {
    width: 22,
    height: 22,
    borderRadius: BorderRadius.full,
    borderWidth: 1.5,
    borderColor: Colors.gray[300],
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  directVehicleRadioSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary,
  },
  directVehicleName: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  directVehicleDetails: {
    marginTop: 3,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
  },
  directVehicleHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  directVehicleHintText: {
    flex: 1,
    color: Colors.gray[700],
    fontSize: FontSizes.xs,
  },
  directPassengerKycCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
    gap: Spacing.sm,
  },
  directPassengerKycCardActive: {
    borderColor: Colors.primary + '55',
    backgroundColor: Colors.primary + '08',
  },
  directPassengerKycCardPressed: {
    opacity: 0.82,
  },
  directPassengerKycIcon: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary + '12',
  },
  directPassengerKycIconActive: {
    backgroundColor: Colors.primary,
  },
  directPassengerKycCopy: {
    flex: 1,
    minWidth: 0,
  },
  directPassengerKycTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  directPassengerKycSubtitle: {
    marginTop: 3,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  directPassengerKycSwitch: {
    width: 42,
    height: 24,
    borderRadius: BorderRadius.full,
    padding: 2,
    justifyContent: 'center',
    backgroundColor: Colors.gray[300],
  },
  directPassengerKycSwitchActive: {
    backgroundColor: Colors.success,
  },
  directPassengerKycThumb: {
    width: 20,
    height: 20,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    alignSelf: 'flex-start',
  },
  directPassengerKycThumbActive: {
    alignSelf: 'flex-end',
  },
  directAcceptModalIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary + '12',
    alignItems: 'center',
    justifyContent: 'center',
  },
  directAcceptModalTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  directAcceptModalCard: {
    height: '85%',
    maxHeight: '85%',
  },
  directAcceptModalScrollContent: {
    padding: Spacing.lg,
    paddingBottom: Spacing.md,
    gap: Spacing.md,
  },
  directAcceptSummaryCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[100],
  },
  directAcceptSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  directAcceptSummaryText: {
    flex: 1,
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  directAcceptModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
    backgroundColor: Colors.white,
  },
  directAcceptSecondaryButton: {
    flex: 1,
    minHeight: 48,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.sm,
  }
});
