import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  driverHeroStatusDot: {
    width: 7,
    height: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
  },
  driverHeroStatusText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  ownerHeroStatusBadge: {
    minHeight: 30,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '12',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  ownerHeroStatusDot: {
    width: 7,
    height: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
  },
  ownerHeroStatusText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  ownerHeroCounter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
  },
  ownerHeroCounterText: {
    color: Colors.white,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  ownerHeroTitle: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    lineHeight: 26,
  },
  ownerHeroSubtitle: {
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
    lineHeight: 20,
  },
  ownerHeroLead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
  },
  ownerHeroLeadIcon: {
    width: 42,
    height: 42,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary + '10',
    borderWidth: 1,
    borderColor: Colors.primary + '18',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ownerHeroLeadCopy: {
    flex: 1,
    minWidth: 0,
  },
  ownerHeroRouteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  ownerHeroRouteDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 5,
    backgroundColor: Colors.white,
  },
  ownerHeroRouteSquare: {
    borderRadius: 3,
    backgroundColor: Colors.primary,
  },
  ownerHeroRouteInfo: {
    flex: 1,
    marginLeft: Spacing.md,
    paddingRight: 46,
  },
  ownerHeroRouteLine: {
    width: 1,
    height: 18,
    backgroundColor: Colors.gray[200],
    marginLeft: 5,
    marginVertical: 6,
  },
  driverRouteCard: {
    padding: Spacing.md,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.gray[900],
    overflow: 'hidden',
  },
  driverRouteLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    color: Colors.gray[400],
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  driverRouteText: {
    marginTop: 4,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.semibold,
    color: Colors.white,
    lineHeight: 22,
  },
  driverRouteLine: {
    backgroundColor: Colors.gray[600],
  },
  driverMapIconButton: {
    position: 'absolute',
    right: Spacing.sm,
    top: Spacing.sm,
    zIndex: 4,
    width: 44,
    height: 44,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.primary + '35',
    backgroundColor: Colors.primary + '18',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverMapIconButtonActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary,
  },
  driverMapIconButtonPressed: {
    opacity: 0.72,
  },
  driverMapIconButtonDisabled: {
    borderColor: Colors.gray[700],
    backgroundColor: Colors.gray[800],
    opacity: 0.72,
  },
  driverInlineMapFrame: {
    height: 180,
    marginHorizontal: -Spacing.md,
    marginTop: Spacing.md,
    marginBottom: -Spacing.md,
    overflow: 'hidden',
    backgroundColor: Colors.gray[200],
  },
  driverInlineMap: {
    width: '100%',
    height: '100%',
  },
  driverMapCaption: {
    position: 'absolute',
    left: Spacing.md,
    top: Spacing.md,
    minHeight: 26,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    shadowColor: Colors.gray[900],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
  },
  driverMapCaptionText: {
    color: Colors.gray[800],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  driverMapMarker: {
    width: 26,
    height: 26,
    borderRadius: BorderRadius.full,
    borderWidth: 3,
    borderColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.gray[900],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  driverMapMarkerDeparture: {
    backgroundColor: Colors.success,
  },
  driverMapMarkerArrival: {
    backgroundColor: Colors.primary,
  },
  driverMapMarkerCore: {
    width: 8,
    height: 8,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
  },
  driverVehicleSpotlight: {
    minHeight: 72,
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '22',
    backgroundColor: Colors.primary + '08',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  ownerVehicleSpotlight: {
    backgroundColor: Colors.white,
    borderColor: Colors.gray[200],
  },
  driverVehicleIconShell: {
    width: 48,
    height: 48,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '18',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  driverVehicleCopy: {
    flex: 1,
    minWidth: 0,
  },
  driverVehicleEyebrow: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  driverVehicleName: {
    marginTop: 2,
    color: Colors.gray[900],
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  driverVehicleHint: {
    marginTop: 2,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 15,
  },
  driverVehicleCheck: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ownerVehicleChoiceIcon: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.primary + '30',
    backgroundColor: Colors.primary + '0D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverFactsRow: {
    minHeight: 78,
    paddingVertical: Spacing.xs,
    flexDirection: 'row',
    alignItems: 'stretch',
  }
});
