import { StyleSheet } from "react-native";

export const f = StyleSheet.create({
  section: { gap: 16 },
  title: { fontSize: 25, fontWeight: "700", color: "#172D3B", lineHeight: 32 },
  small: { fontSize: 13, color: "#647582", lineHeight: 19 },
  intro: { gap: 6, marginBottom: 4 },
  progress: { flexDirection: "row", gap: 10 },
  progressItem: { flex: 1, gap: 7 },
  progressTrack: { height: 3, backgroundColor: "#E8EDF0", borderRadius: 2 },
  progressActive: { backgroundColor: "#D84D16" },
  progressLabel: { color: "#647582", fontSize: 12 },
  progressSelected: { color: "#A83B13", fontWeight: "700" },
  field: { gap: 7 },
  input: {
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DAE1E6",
    backgroundColor: "#F8FAFB",
    color: "#172D3B",
    fontSize: 16,
  },
  inputFocused: { borderColor: "#D84D16", backgroundColor: "#FFF" },
  inputError: { borderColor: "#B42318" },
  multiline: { minHeight: 104, textAlignVertical: "top" },
  options: {
    borderWidth: 1,
    borderColor: "#E1E7EB",
    borderRadius: 14,
    overflow: "hidden",
  },
  option: {
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FFF",
  },
  optionDivider: { borderTopWidth: 1, borderTopColor: "#EDF0F2" },
  optionSelected: { backgroundColor: "#FFF6EF" },
  optionLabel: { flex: 1, fontSize: 15, lineHeight: 21, color: "#344A58" },
  selectedLabel: { color: "#9E3913", fontWeight: "600" },
  disclosure: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
  },
  disclosureText: {
    flex: 1,
    fontSize: 15,
    color: "#344A58",
    fontWeight: "600",
  },
  optional: { borderTopWidth: 1, borderTopColor: "#E7EBEE", gap: 8 },
  reviewSection: {
    borderBottomWidth: 1,
    borderBottomColor: "#E7EBEE",
    paddingBottom: 18,
    gap: 8,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  edit: { minHeight: 44, justifyContent: "center", paddingHorizontal: 6 },
  editLabel: { fontSize: 14, fontWeight: "600", color: "#B34117" },
  reviewValue: { color: "#172D3B", fontSize: 16, lineHeight: 24 },
  bullet: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#D84D16" },
  consent: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 12,
    alignItems: "flex-start",
    minHeight: 48,
  },
  reassurance: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    backgroundColor: "#F0F5F7",
    padding: 14,
    borderRadius: 12,
  },
  footerNote: { fontSize: 12, textAlign: "center", color: "#647582" },
  success: { paddingTop: 24, gap: 18 },
  successIcon: {
    width: 64,
    height: 64,
    borderRadius: 22,
    backgroundColor: "#EAF5EE",
    justifyContent: "center",
    alignItems: "center",
  },
  nextStep: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    paddingVertical: 12,
  },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EDF2F5",
    color: "#405568",
    textAlign: "center",
    lineHeight: 28,
    fontWeight: "700",
  },
});
