import { BorderRadius, Colors, CommonStyles, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  passengerOverviewHeader: { flexDirection: 'column', alignItems: 'stretch' },
  becomeDriverButton: { maxWidth: '100%', minHeight: 48, paddingVertical: Spacing.sm },
  identitySection: { paddingVertical: Spacing.sm, gap: Spacing.xs, borderBottomWidth: 1, borderBottomColor: Colors.gray[100] },
  identityHeading: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  identityTitle: { flex: 1, color: Colors.gray[900], fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  identityHint: { color: Colors.gray[600], fontSize: FontSizes.xs, lineHeight: 18 },
  identityAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  identityActionText: { color: Colors.primary, fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, flexShrink: 1 },
  profileOverviewPanel: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    padding: Spacing.md,
    gap: Spacing.md,
    ...CommonStyles.shadowSm,
  },
  profileOverviewHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  profileOverviewTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  profileOverviewTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  profileOverviewSubtitle: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  profileOverviewCta: {
    maxWidth: '58%',
    minHeight: 40,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
  },
  profileOverviewCtaDisabled: {
    opacity: 0.65,
  },
  profileOverviewCtaText: {
    flexShrink: 1,
    color: Colors.white,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  driverStatusGrid: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  driverStatusItem: {
    flex: 1,
    minHeight: 76,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.gray[50],
    padding: Spacing.sm,
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 3,
  },
  driverStatusIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  driverStatusLabel: {
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  driverStatusValue: {
    maxWidth: '100%',
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  profileAlert: {
    minHeight: 44,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.danger + '24',
    backgroundColor: Colors.danger + '08',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  profileAlertText: {
    flex: 1,
    color: Colors.danger,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    lineHeight: 17,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  quickActionButton: {
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 76,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.white,
    padding: Spacing.sm,
    justifyContent: 'center',
    gap: 4,
  },
  quickActionIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionBadge: {
    position: 'absolute',
    top: -5,
    right: -7,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.warning,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  quickActionBadgeText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: FontWeights.bold,
  },
  quickActionLabel: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  quickActionMeta: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
  },
});
