import { BorderRadius, Colors, CommonStyles, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  subscriptionModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  subscriptionModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  subscriptionModalCard: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    maxHeight: '82%',
    paddingTop: Spacing.sm,
    overflow: 'hidden',
    ...CommonStyles.shadowLg,
  },
  subscriptionModalHandle: {
    width: 48,
    height: 5,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[300],
    alignSelf: 'center',
    marginBottom: Spacing.sm,
  },
  subscriptionModalHero: {
    paddingHorizontal: Spacing.xl,
    paddingTop: 6,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  subscriptionHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  subscriptionHeaderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.primary + '18',
    backgroundColor: Colors.primary + '10',
  },
  subscriptionHeaderBadgeText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  subscriptionModalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white + 'D9',
  },
  subscriptionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: Spacing.md,
  },
  subscriptionModalHeaderTextBlock: {
    flex: 1,
    gap: Spacing.xs,
  },
  subscriptionModalTitle: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  subscriptionModalSubtitle: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    lineHeight: 20,
  },
  subscriptionModalPricePill: {
    minWidth: 112,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.lg,
    alignItems: 'flex-end',
    borderWidth: 1,
    borderColor: Colors.primary + '16',
    backgroundColor: Colors.white + 'F2',
    ...CommonStyles.shadowSm,
  },
  subscriptionModalPrice: {
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  subscriptionModalPriceCaption: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  subscriptionStepIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    backgroundColor: Colors.white,
  },
  subscriptionStepPill: {
    flex: 1,
    minHeight: 34,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.gray[50],
  },
  subscriptionStepPillActive: {
    borderColor: Colors.primary + '35',
    backgroundColor: Colors.primary + '08',
  },
  subscriptionStepText: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  subscriptionStepTextActive: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  subscriptionModalScroll: {
    flexShrink: 1,
    maxHeight: 320,
  },
  subscriptionModalContent: {
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  subscriptionSummaryCard: {
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary + '07',
    borderWidth: 1,
    borderColor: Colors.primary + '16',
    padding: Spacing.lg,
  },
  subscriptionSummaryPrice: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    color: Colors.primary,
  },
  subscriptionSummaryText: {
    marginTop: Spacing.xs,
    fontSize: FontSizes.sm,
    color: Colors.gray[700],
    lineHeight: 20,
  },
  subscriptionSectionLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: Colors.gray[800],
  },
  subscriptionPaymentGrid: {
    gap: Spacing.sm,
  },
  subscriptionPaymentOption: {
    minHeight: 58,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  subscriptionPaymentOptionActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '08',
  },
  subscriptionPaymentOptionText: {
    flex: 1,
  },
  subscriptionSelectedMethodCard: {
    minHeight: 58,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.primary + '25',
    backgroundColor: Colors.primary + '08',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  subscriptionChangeMethodButton: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '20',
  },
  subscriptionChangeMethodText: {
    color: Colors.primary,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  subscriptionPaymentOptionLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  subscriptionPaymentOptionHint: {
    marginTop: 2,
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
  },
  subscriptionPhoneSection: {
    gap: Spacing.sm,
  },
  subscriptionPhoneInputWrapper: {
    minHeight: 52,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  subscriptionPhoneInput: {
    flex: 1,
    fontSize: FontSizes.base,
    color: Colors.gray[900],
  },
  subscriptionInputHint: {
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
    lineHeight: 17,
  },
  subscriptionProgressPanel: {
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    gap: 0,
  },
  subscriptionProgressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 54,
  },
  subscriptionProgressRail: {
    width: 30,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  subscriptionProgressDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscriptionProgressLine: {
    width: 2,
    flex: 1,
    minHeight: 24,
    marginVertical: 3,
    borderRadius: 1,
  },
  subscriptionProgressTextBlock: {
    flex: 1,
    paddingLeft: Spacing.sm,
    paddingBottom: Spacing.md,
  },
  subscriptionProgressTitle: {
    color: Colors.gray[500],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  subscriptionProgressDescription: {
    marginTop: 2,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  subscriptionPrimaryButton: {
    minHeight: 48,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
  },
  subscriptionPrimaryButtonText: {
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  subscriptionSecondaryButton: {
    minHeight: 46,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.primary + '35',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
  },
  subscriptionSecondaryButtonText: {
    color: Colors.primary,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  subscriptionButtonDisabled: {
    opacity: 0.6,
  },
  subscriptionFixedFooter: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xs,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
    backgroundColor: Colors.white,
    gap: Spacing.sm,
  },
  subscriptionFooterStatusPanel: {
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary + '08',
    borderWidth: 1,
    borderColor: Colors.primary + '22',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  subscriptionFooterStatusIcon: {
    width: 24,
    minHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscriptionFooterStatusContent: {
    flex: 1,
    gap: 2,
  },
  subscriptionFooterStatusTitle: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  subscriptionFooterStatusText: {
    color: Colors.gray[700],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  subscriptionFooterStatusReference: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  paymentButtonContainer: {
    gap: Spacing.sm,
  },
});
