import { StyleSheet } from "react-native";
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  keyboardAvoiding: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  card: {
    width: '100%',
    height: '90%',
    maxHeight: '96%',
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    shadowColor: Colors.black,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -5 },
    elevation: 16,
  },
  cardWithKeyboard: {
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
  },
  safeArea: {
    flex: 1,
    width: '100%',
  },
  scroll: { flex: 1, minHeight: 0 },
  header: {
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  headerWithKeyboard: {
    minHeight: 56,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xs,
  },
  badge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeWithKeyboard: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: Colors.gray[900],
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
  },
  titleWithKeyboard: {
    fontSize: FontSizes.lg,
  },
  subtitle: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
    marginTop: 2,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.gray[50],
  },
  content: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.xs,
    gap: Spacing.md,
  },
  contentWithKeyboard: {
    gap: Spacing.sm,
  },
  inputGroup: {
    gap: 6,
  },
  sectionLabel: {
    color: Colors.gray[700],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  vehicleTypeList: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 6,
  },
  vehicleTypeOption: {
    position: 'relative',
    flex: 1,
    minWidth: 0,
    minHeight: 126,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.white,
    paddingHorizontal: 6,
    paddingVertical: Spacing.sm,
  },
  vehicleTypeOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '0D',
  },
  vehicleTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.gray[100],
  },
  vehicleTypeIconSelected: {
    backgroundColor: Colors.primary + '18',
  },
  vehicleTypeCopy: {
    width: '100%',
    alignItems: 'center',
    gap: 3,
    marginTop: 6,
  },
  vehicleTypeLabel: {
    color: Colors.gray[800],
    fontSize: FontSizes.xs,
    lineHeight: 15,
    fontWeight: FontWeights.bold,
    textAlign: 'center',
  },
  vehicleTypeLabelSelected: {
    color: Colors.primaryDark,
  },
  vehicleTypeDescription: {
    color: Colors.gray[500],
    fontSize: 10,
    lineHeight: 13,
    textAlign: 'center',
  },
  selectionDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Colors.gray[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionDotSelected: {
    borderColor: Colors.primary,
  },
  selectionDotCore: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
  },
  fieldsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  fieldCell: {
    width: '48%',
    flexGrow: 1,
    flexBasis: '46%',
    gap: 4,
  },
  label: {
    color: Colors.gray[700],
    fontSize: 11,
    fontWeight: FontWeights.bold,
  },
  input: {
    minHeight: 48,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
  },
  inputWithKeyboard: {
    minHeight: 42,
    paddingVertical: 7,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.24)',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  errorText: {
    flex: 1,
    color: Colors.danger,
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  actions: {
    flexShrink: 0,
    flexDirection: 'row',
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
  },
  actionButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: BorderRadius.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButton: {
    backgroundColor: Colors.primary,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  secondaryButton: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.gray[300],
  },
  primaryButtonText: {
    color: Colors.white,
    fontWeight: FontWeights.bold,
    fontSize: FontSizes.base,
  },
  secondaryButtonText: {
    color: Colors.gray[700],
    fontWeight: FontWeights.bold,
    fontSize: FontSizes.base,
  }
});
