import { StyleSheet } from "react-native";
import {
  AUTH_SURFACE,
  AUTH_BACKGROUND,
  AUTH_WARM_SURFACE,
  AUTH_WARM_BORDER,
  AUTH_MUTED_TEXT,
} from '@/features/auth/authColors';
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AUTH_BACKGROUND,
  },
  // Header
  header: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: 0,
  },
  headerTop: {
    minHeight: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTopCentered: {
    justifyContent: 'center',
  },
  backButton: {
    position: 'absolute',
    left: 0,
    width: 42,
    height: 42,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBrand: {
    fontSize: FontSizes.xxl,
    fontWeight: FontWeights.bold,
    color: Colors.primaryDark,
    textAlign: 'center',
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: AUTH_SURFACE,
    borderRadius: BorderRadius.full,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.primary + '18',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  toggleButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: BorderRadius.full,
  },
  toggleButtonActive: {
    backgroundColor: AUTH_WARM_SURFACE,
  },
  toggleText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[500],
  },
  toggleTextActive: {
    color: Colors.primaryDark,
  },
  progressContainer: {
    alignItems: 'center',
    marginTop: Spacing.md,
  },
  progressBarBg: {
    width: '100%',
    height: 4,
    backgroundColor: Colors.gray[200],
    borderRadius: BorderRadius.full,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.full,
  },
  motivationalText: {
    textAlign: 'center',
    color: AUTH_MUTED_TEXT,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    marginTop: 6,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.lg,
    flexGrow: 1,
  },
  stepContainer: {
    flex: 1,
  },
  phoneStepContainer: {
    paddingBottom: Spacing.md,
  },
  // Brand / hero
  brandHero: {
    alignItems: 'center',
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
  },
  brandIcon: {
    width: 48,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.xs,
  },
  brandName: {
    fontSize: 38,
    fontWeight: FontWeights.bold,
    color: Colors.primaryDark,
  },
  introBlock: {
    marginTop: 0,
    marginBottom: Spacing.lg,
  },
  referralNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '35',
    backgroundColor: AUTH_WARM_SURFACE,
  },
  referralNoticeIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary + '18',
  },
  referralNoticeContent: {
    flex: 1,
    minWidth: 0,
  },
  referralNoticeTitle: {
    color: Colors.primaryDark,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  referralNoticeText: {
    marginTop: 3,
    color: AUTH_MUTED_TEXT,
    fontSize: FontSizes.xs,
    lineHeight: 18,
  },
  introTitle: {
    fontSize: 28,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    marginBottom: Spacing.xs,
  },
  introSubtitle: {
    fontSize: FontSizes.base,
    color: AUTH_MUTED_TEXT,
    lineHeight: 23,
  },
  heroSection: {
    alignItems: 'center',
    marginTop: Spacing.xl,
    marginBottom: Spacing.xl,
  },
  heroSectionCompact: {
    alignItems: 'center',
    marginTop: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  logoContainer: {
    width: 92,
    height: 92,
    borderRadius: 30,
    backgroundColor: Colors.primary + '12',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '18',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    marginBottom: Spacing.sm,
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: FontSizes.base,
    color: AUTH_MUTED_TEXT,
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: Spacing.md,
  },
  secureIllustration: {
    width: 168,
    height: 168,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.xl,
  },
  secureIllustrationCompact: {
    width: 88,
    height: 88,
    marginBottom: Spacing.sm,
  },
  secureRing: {
    position: 'absolute',
    width: 142,
    height: 142,
    borderRadius: BorderRadius.full,
    borderWidth: 6,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  secureRingCompact: {
    width: 76,
    height: 76,
    borderWidth: 4,
  },
  secureConnector: {
    position: 'absolute',
    width: 118,
    height: 24,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
  },
  secureConnectorCompact: {
    width: 62,
    height: 14,
  },
  secureTile: {
    width: 96,
    height: 96,
    borderRadius: 24,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-6deg' }],
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 6,
  },
  secureTileCompact: {
    width: 56,
    height: 56,
    borderRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 3,
  },
  // Forms
  formSection: {
    gap: Spacing.md,
    marginTop: Spacing.lg,
  },
  authCard: {
    backgroundColor: AUTH_SURFACE,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: AUTH_WARM_BORDER,
    padding: Spacing.lg,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  inputLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: '#604238',
    marginBottom: 8,
    textTransform: 'uppercase',
  }
});
