import { StyleSheet } from "react-native";
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";

export const styles = StyleSheet.create({
  channelTitle: {
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  channelTitleSelected: {
    color: Colors.primaryDark,
  },
  channelDescription: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
    marginTop: 2,
  },
  phoneCard: {
    marginTop: Spacing.md,
  },
  phoneInputRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  phoneInputRowInvalid: {
    borderColor: Colors.danger,
    backgroundColor: '#FEF2F2',
  },
  phoneInput: {
    flex: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.base,
    fontWeight: FontWeights.semibold,
    paddingVertical: 0,
  },
  phoneHint: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
    marginTop: Spacing.xs,
  },
  phoneHintInvalid: {
    color: Colors.dangerDark,
  },
  resumePaymentButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.primary + '40',
    backgroundColor: Colors.primary + '08',
  },
  resumePaymentText: {
    color: Colors.primary,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  successBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginTop: Spacing.lg,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: '#EAF9F0',
  },
  successCopy: { flex: 1 },
  successTitle: { color: Colors.successDark, fontWeight: FontWeights.bold },
  successText: { color: Colors.gray[600], fontSize: FontSizes.xs, marginTop: 2 },
  summaryRows: {
    marginTop: Spacing.lg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.gray[200],
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.gray[200],
  },
  summaryLabel: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
  },
  summaryValue: {
    flex: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    textAlign: 'right',
  },
  summaryActions: {
    gap: Spacing.sm,
  },
  invoiceButton: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '40',
    shadowOpacity: 0,
    elevation: 0,
  },
  invoiceButtonText: {
    color: Colors.primary,
  },
  statusBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: '#EAF4FC',
  },
  statusText: { flex: 1, color: Colors.infoDark, fontSize: FontSizes.sm, lineHeight: 19 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: '#FEF2F2',
  },
  errorText: { flex: 1, color: Colors.dangerDark, fontSize: FontSizes.sm, lineHeight: 19 },
  payButton: {
    minHeight: 56,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 5,
  },
  payButtonDisabled: { opacity: 0.55 },
  payButtonText: {
    color: Colors.white,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    textAlign: 'center',
  }
});
