import { StyleSheet } from "react-native";
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(17, 24, 39, 0.58)',
  },
  keyboardAvoidingView: {
    justifyContent: 'flex-end',
  },
  sheet: {
    maxHeight: '92%',
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
  },
  handle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[300],
    marginBottom: Spacing.lg,
  },
  content: {
    paddingBottom: Spacing.lg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  arrivalIcon: {
    width: 54,
    height: 54,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
  },
  summaryIcon: {
    backgroundColor: Colors.success,
  },
  headerCopy: { flex: 1 },
  eyebrow: {
    color: Colors.successDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    letterSpacing: 0.7,
  },
  title: {
    color: Colors.gray[900],
    fontSize: FontSizes.xxl,
    fontWeight: FontWeights.bold,
    marginTop: 2,
  },
  destinationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.lg,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.gray[50],
  },
  destination: {
    flex: 1,
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  amountCard: {
    marginTop: Spacing.md,
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    backgroundColor: '#FFF5F0',
    borderWidth: 1,
    borderColor: '#FFD9CA',
  },
  amountLabel: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  amountValue: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xxxl,
    fontWeight: FontWeights.bold,
    marginTop: Spacing.xs,
  },
  amountHint: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 18,
    marginTop: Spacing.sm,
  },
  sectionTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  pointsRecommendation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: '#F2C94C',
    backgroundColor: '#FFF9DF',
  },
  pointsRecommendationIcon: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFE9C8',
  },
  pointsRecommendationCopy: { flex: 1 },
  pointsRecommendationTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  pointsRecommendationText: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
    marginTop: 2,
  },
  pointsRecommendationAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  pointsRecommendationActionText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  options: { gap: Spacing.sm },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  optionSelected: {
    borderColor: Colors.primary,
    backgroundColor: '#FFF8F5',
  },
  optionRecommended: {
    borderColor: '#F2C94C',
    backgroundColor: '#FFFCED',
  },
  optionIcon: {
    width: 42,
    height: 42,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.gray[100],
  },
  optionIconSelected: { backgroundColor: '#FFEAE1' },
  optionCopy: { flex: 1 },
  optionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  optionTitle: {
    color: Colors.gray[800],
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  optionTitleSelected: { color: Colors.primaryDark },
  recommendedBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
  },
  recommendedBadgeText: {
    color: Colors.white,
    fontSize: 9,
    fontWeight: FontWeights.bold,
    letterSpacing: 0.4,
  },
  optionDescription: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
    marginTop: 2,
  },
  pointsCard: {
    marginTop: Spacing.md,
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    backgroundColor: '#FFFBEA',
    borderWidth: 1,
    borderColor: '#FCE7A3',
  },
  pointsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pointsLabel: { color: Colors.gray[600], fontSize: FontSizes.xs },
  pointsBalance: {
    color: Colors.gray[900],
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    marginTop: 2,
  },
  walletBadge: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  breakdownDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#EAD997',
    marginVertical: Spacing.md,
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  breakdownLabel: { color: Colors.gray[600], fontSize: FontSizes.sm },
  breakdownValue: {
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    textAlign: 'right',
  },
  complementValue: { color: Colors.primaryDark },
  pointsHint: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 18,
    marginTop: Spacing.xs,
  },
  electronicCard: {
    marginTop: Spacing.md,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
  },
  paymentFieldLabel: {
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    marginBottom: Spacing.sm,
  },
  channelGrid: {
    gap: Spacing.sm,
  },
  channelOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  channelOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: '#FFF8F5',
  },
  channelCopy: {
    flex: 1,
  }
});
