import { type AddressInputMode } from '@/components/AddressEntryModeSelector';
import { type AddressSectionStep } from '@/components/AddressSectionSlider';
import LocationPickerModal, { MapLocationSelection } from '@/components/LocationPickerModal';
import { useDialog } from '@/components/ui/DialogProvider';
import {
  ELECTRONIC_PAYMENTS_ENABLED,
} from '@/constants/paymentFeatures';
import { MUTATION_RECONCILIATION_DELAYS_MS } from '@/constants/network';
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from '@/constants/styles';
import { REGISTERED_VEHICLE_TYPE_OPTIONS } from '@/constants/vehicleTypes';
import { useUserLocation } from '@/hooks/useUserLocation';
import { trackEvent } from '@/services/analytics';
import { useGeocodeMutation } from '@/store/api/googleMapsApi';
import {
  useCreateTripRequestMutation,
  useGetTripRequestVehicleOptionsMutation,
  useLazyGetMyTripRequestsQuery,
  type TripRequestVehiclePriceOption,
} from '@/store/api/tripRequestApi';
import { useGetFavoriteLocationsQuery } from '@/store/api/userApi';
import type { FavoriteLocation, TripPaymentMode, TripRequestVehicleType } from '@/types';
import { buildCurrentLocationSelection } from '@/utils/currentLocationSelection';
import { getApiErrorMessage, isAmbiguousTransportError } from '@/utils/errorHelpers';
import {
  buildManualGeocodeQuery,
  MANUAL_GEOCODE_DEBOUNCE_MS,
  mapGeocodeResponseToSelection,
  type ManualGeocodeStatus,
} from '@/utils/manualAddressGeocode';
import Animated, { FadeIn, FadeOut } from '@/utils/reanimated';
import { getTripRequestDetailHref } from '@/utils/requestNavigation';
import { getRouteCoordinates } from '@/utils/routeApi';
import { normalizeTripMapCoordinate } from '@/utils/tripCoordinates';
import { Ionicons } from '@expo/vector-icons';
import DateTimePicker, {
  DateTimePickerAndroid,
  type DateTimePickerEvent,
} from '@react-native-community/datetimepicker';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { startTransition, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  AppState,
  InteractionManager,
  Keyboard,
  KeyboardAvoidingView,
  Modal,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  type ImageRequireSource,
} from 'react-native';
import MapView, { Marker, Polyline, PROVIDER_GOOGLE, type Region } from 'react-native-maps';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

export const requestStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#EEF2F6' },
  flex: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, backgroundColor: '#EEF2F6' },
  headerButton: { width: 40, height: 40, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.white, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  headerTitle: { fontSize: FontSizes.lg, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  headerSpacer: { width: 40, height: 40 },
  content: { paddingBottom: Spacing.lg },
  routeContent: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.md },
  detailsContent: { paddingHorizontal: 0, paddingBottom: 116 },
  mapPreview: { height: 240, overflow: 'hidden', backgroundColor: Colors.gray[200] },
  detailsMapPreview: { height: 190, borderRadius: BorderRadius.sm, borderWidth: 1, borderColor: Colors.gray[200] },
  mapPreviewMap: { ...StyleSheet.absoluteFillObject },
  mapPreviewShade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 78, backgroundColor: 'rgba(238,242,246,0.72)' },
  mapLocateButton: { position: 'absolute', right: Spacing.lg, top: Spacing.md, minHeight: 42, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, backgroundColor: Colors.white, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 4 },
  mapLocateButtonText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  routeStatusBadge: { position: 'absolute', left: Spacing.lg, bottom: Spacing.lg, minHeight: 38, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, backgroundColor: Colors.white, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 4 },
  routeStatusText: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[800] },
  routeSetup: { backgroundColor: Colors.white, borderRadius: BorderRadius.lg, padding: Spacing.lg, paddingBottom: Spacing.xxl, gap: Spacing.lg, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 5 },
  routeSetupHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  routeSetupTitle: { fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  routeSetupSwap: { width: 42, height: 42, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary + '12' },
  routeInputStack: { borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], overflow: 'hidden', backgroundColor: Colors.white },
  routePickerItem: { backgroundColor: Colors.white },
  routePickerButton: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingHorizontal: Spacing.md },
  routePickerIcon: { width: 42, height: 42, borderRadius: BorderRadius.sm, alignItems: 'center', justifyContent: 'center' },
  routePickerIconStart: { backgroundColor: Colors.success + '14' },
  routePickerIconEnd: { backgroundColor: Colors.primary + '14' },
  routePickerCopy: { flex: 1, minWidth: 0 },
  routePickerLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[500], textTransform: 'uppercase' },
  routePickerValue: { marginTop: 3, fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  routePickerPlaceholder: { color: Colors.gray[500], fontWeight: FontWeights.semibold },
  routeManualWrap: { paddingHorizontal: Spacing.md, paddingBottom: Spacing.md, gap: Spacing.xs },
  routeManualInput: { minHeight: 46, borderRadius: BorderRadius.sm, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], paddingHorizontal: Spacing.md, fontSize: FontSizes.base, color: Colors.gray[900] },
  routeStackDivider: { height: 1, backgroundColor: Colors.gray[100], marginLeft: 66 },
  routeVehicleChoice: { gap: Spacing.sm },
  routeVehicleChoiceHeader: { gap: 2 },
  routeVehicleChoiceTitle: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  routeVehicleChoiceSubtitle: { fontSize: FontSizes.xs, color: Colors.gray[500] },
  routeVehicleChoiceRow: { flexDirection: 'row', alignItems: 'stretch', gap: 6 },
  routeVehicleChoiceOption: { position: 'relative', flex: 1, minWidth: 0, minHeight: 92, borderRadius: BorderRadius.md, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 5, paddingVertical: Spacing.sm },
  routeVehicleChoiceOptionSelected: { borderColor: Colors.primary, backgroundColor: Colors.primary + '0D' },
  routeVehicleChoiceIcon: { width: 36, height: 36, borderRadius: BorderRadius.full, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center' },
  routeVehicleChoiceIconSelected: { backgroundColor: Colors.primary + '16' },
  routeVehicleChoiceLabel: { minHeight: 30, fontSize: FontSizes.xs, lineHeight: 15, fontWeight: FontWeights.bold, color: Colors.gray[700], textAlign: 'center' },
  routeVehicleChoiceLabelSelected: { color: Colors.primaryDark },
  routeVehicleChoiceCheck: { position: 'absolute', top: 6, right: 6 },
  routeQuickRow: { flexDirection: 'row', gap: Spacing.sm },
  routeQuickButton: { flex: 1, minHeight: 48, borderRadius: BorderRadius.full, backgroundColor: Colors.primary + '10', borderWidth: 1, borderColor: Colors.primary + '20', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
  routeQuickText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.primary },
  routeSuggestions: { gap: Spacing.sm },
  offerFlow: { flex: 1, backgroundColor: '#EEF2F6' },
  offerMap: { height: 300, overflow: 'hidden', backgroundColor: Colors.gray[200] },
  offerMapShade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 96, backgroundColor: 'rgba(238,242,246,0.35)' },
  offerMapBack: { position: 'absolute', left: Spacing.lg, bottom: Spacing.xl, width: 48, height: 48, borderRadius: BorderRadius.full, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center', shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 4 },
  offerRouteCard: { position: 'absolute', left: Spacing.lg, right: Spacing.lg, top: Spacing.md, borderRadius: BorderRadius.lg, backgroundColor: Colors.white, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 18, elevation: 6 },
  offerRouteRow: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  offerRouteDivider: { height: 1, backgroundColor: Colors.gray[100], marginLeft: 26 },
  offerRouteText: { flex: 1, fontSize: FontSizes.base, fontWeight: FontWeights.semibold, color: Colors.gray[900] },
  offerSheet: { marginTop: -18, borderTopLeftRadius: BorderRadius.xl, borderTopRightRadius: BorderRadius.xl, backgroundColor: Colors.white, paddingHorizontal: Spacing.lg, paddingTop: Spacing.md, paddingBottom: Spacing.lg, gap: Spacing.sm },
  vehicleChoiceLoading: { minHeight: 72, borderRadius: BorderRadius.lg, backgroundColor: Colors.gray[50], flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
  vehicleChoiceLoadingText: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[600] },
  vehicleChoiceError: { minHeight: 72, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.danger + '30', backgroundColor: Colors.danger + '08', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, paddingHorizontal: Spacing.md },
  vehicleChoiceErrorCopy: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  vehicleChoiceErrorText: { flex: 1, fontSize: FontSizes.sm, color: Colors.gray[700] },
  vehicleChoiceRetry: { minHeight: 36, borderRadius: BorderRadius.full, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.md },
  vehicleChoiceRetryText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.primary },
  offerPriceControl: { minHeight: 98, borderRadius: BorderRadius.lg, backgroundColor: '#F7F8FA', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.md },
  offerPriceButton: { width: 50, height: 50, borderRadius: BorderRadius.full, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center', shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  offerPriceButtonDisabled: { backgroundColor: Colors.gray[100] },
  offerPriceCenter: { flex: 1, alignItems: 'center', paddingHorizontal: Spacing.sm },
  offerPriceValue: { fontSize: FontSizes.xxl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  offerPriceHint: { marginTop: 2, fontSize: FontSizes.sm, color: Colors.gray[600], textAlign: 'center' },
  offerPriceTotal: { marginTop: 4, fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.primaryDark, textAlign: 'center' },
  offerOptionsRow: { minHeight: 58, borderRadius: BorderRadius.lg, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.gray[100], flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs },
  offerOptionCopy: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  offerOptionIcon: { width: 34, height: 34, borderRadius: BorderRadius.full, backgroundColor: Colors.primary + '10', alignItems: 'center', justifyContent: 'center' },
  offerOptionTextBlock: { flex: 1, minWidth: 0 },
  offerOptionLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[500] },
  offerOptionText: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  offerPaymentBlock: { gap: Spacing.sm },
  offerPaymentOption: { minHeight: 58, borderRadius: BorderRadius.md, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.gray[100], flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm },
  offerPaymentOptionSelected: { borderColor: Colors.primary, backgroundColor: Colors.primary + '08' },
  offerPaymentCopy: { flex: 1, minWidth: 0 },
  offerPaymentTitle: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  offerPaymentText: { marginTop: 2, fontSize: 12, color: Colors.gray[500] },
  offerTimeCompactBlock: { gap: Spacing.sm, marginBottom: Spacing.xs, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.primary + '18', backgroundColor: '#FFF7F2', padding: Spacing.sm },
  offerTimeCompactRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  offerTimeCompactIcon: { width: 36, height: 36, borderRadius: BorderRadius.full, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.primary + '18' },
  offerTimeCompactCopy: { flex: 1, minWidth: 0 },
  offerTimeCompactLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[500] },
  offerTimeCompactValue: { marginTop: 2, fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900], textTransform: 'capitalize' },
  offerPresetCompactScroll: { gap: Spacing.xs, paddingRight: Spacing.lg },
  offerPresetCompact: { minHeight: 34, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.white, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 },
  offerPresetCompactText: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  customCompactWrap: { gap: Spacing.xs, borderTopWidth: 1, borderTopColor: Colors.primary + '14', paddingTop: Spacing.xs },
  customDateTimeRow: { flexDirection: 'row', gap: Spacing.xs },
  customPickerPill: { flex: 1, minHeight: 38, borderRadius: BorderRadius.full, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.primary + '18', paddingHorizontal: Spacing.sm, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  customPickerPillText: { flex: 1, minWidth: 0, fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  flexCompactRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
  flexCompactLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[500], marginRight: 2 },
  flexCompactChip: { minHeight: 30, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.white, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' },
  flexCompactChipText: { fontSize: 11, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  offerTimeBlock: { gap: Spacing.md, marginBottom: Spacing.sm, borderRadius: BorderRadius.xl, borderWidth: 1, borderColor: Colors.primary + '24', backgroundColor: '#FFF7F2', padding: Spacing.lg },
  offerTimeHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  offerTimeHeaderIcon: { width: 44, height: 44, borderRadius: BorderRadius.full, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center', shadowColor: Colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 3 },
  offerTimeHeaderCopy: { flex: 1, minWidth: 0 },
  offerTimeTitle: { fontSize: FontSizes.lg, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  offerTimeSubtitle: { marginTop: 2, fontSize: FontSizes.sm, color: Colors.gray[600] },
  offerSectionLabel: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  offerPresetScroll: { gap: Spacing.sm, paddingRight: Spacing.lg },
  offerPreset: { minHeight: 40, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.white, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: 6 },
  offerPresetActive: { borderColor: Colors.primary, backgroundColor: Colors.primary },
  offerPresetText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  offerPresetTextActive: { color: Colors.white },
  offerTimeSummary: { minHeight: 96, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.primary + '20', backgroundColor: Colors.white, flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md },
  offerTimeSummaryCopy: { flex: 1, minWidth: 0 },
  offerTimeDate: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[600], textTransform: 'capitalize' },
  offerTimeValue: { marginTop: 3, fontSize: 28, lineHeight: 32, fontWeight: FontWeights.bold, color: Colors.primaryDark, letterSpacing: -0.5 },
  offerTimePresetBadge: { maxWidth: 104, minHeight: 34, borderRadius: BorderRadius.full, backgroundColor: Colors.primary + '12', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingHorizontal: Spacing.sm },
  offerTimePresetBadgeText: { flexShrink: 1, fontSize: 11, lineHeight: 13, fontWeight: FontWeights.bold, color: Colors.primaryDark, textAlign: 'center' },
  offerSubmitButton: { minHeight: 58, borderRadius: BorderRadius.lg, backgroundColor: Colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, shadowColor: Colors.primary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.24, shadowRadius: 14, elevation: 6 },
  offerStickyFooter: { backgroundColor: Colors.white, borderTopWidth: 1, borderTopColor: Colors.gray[100], paddingHorizontal: Spacing.lg, paddingTop: Spacing.sm, paddingBottom: Spacing.sm, shadowColor: '#0F172A', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.08, shadowRadius: 14, elevation: 10 },
  offerSubmitText: { color: Colors.white, fontSize: FontSizes.lg, fontWeight: FontWeights.bold },
  offerNoteToggle: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
  offerNoteToggleText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  offerNotePanel: { gap: Spacing.sm },
  rideSheet: { marginHorizontal: Spacing.lg, marginTop: Spacing.md, borderRadius: BorderRadius.xl, backgroundColor: Colors.white, padding: Spacing.md, gap: Spacing.md, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 10 },
  sheetHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: BorderRadius.full, backgroundColor: Colors.gray[200], marginBottom: 2 },
  rideSheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md },
  rideSheetTitle: { fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  rideSheetSubtitle: { marginTop: 2, fontSize: FontSizes.sm, color: Colors.gray[500] },
  sheetSwapButton: { width: 42, height: 42, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: `${Colors.primary}12`, borderWidth: 1, borderColor: `${Colors.primary}24` },
  rideRouteBox: { flexDirection: 'row', gap: Spacing.sm, borderRadius: BorderRadius.lg, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: Colors.gray[200], padding: Spacing.sm },
  rideRail: { width: 22, alignItems: 'center', paddingTop: 22, paddingBottom: 22 },
  rideRailDot: { width: 10, height: 10, borderRadius: BorderRadius.full },
  rideRailDotStart: { backgroundColor: Colors.success },
  rideRailDotEnd: { backgroundColor: Colors.primary },
  rideRailLine: { flex: 1, width: 2, backgroundColor: Colors.gray[300], marginVertical: 5, borderRadius: BorderRadius.full },
  rideFields: { flex: 1 },
  rideLocationBlock: { borderRadius: BorderRadius.md, borderWidth: 1, borderColor: 'transparent', backgroundColor: Colors.white, padding: Spacing.sm, gap: Spacing.xs },
  rideLocationBlockFocused: { borderColor: `${Colors.primary}45`, backgroundColor: `${Colors.primary}06` },
  rideLocationButton: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  rideLocationTextBlock: { flex: 1, minWidth: 0 },
  rideLocationLabel: { fontSize: 11, fontWeight: FontWeights.bold, color: Colors.gray[500], textTransform: 'uppercase' },
  rideLocationValue: { marginTop: 2, fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  rideLocationPlaceholder: { color: Colors.gray[500], fontWeight: FontWeights.semibold },
  rideEditButton: { width: 34, height: 34, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray[50], borderWidth: 1, borderColor: Colors.gray[200] },
  rideManualInput: { minHeight: 42, borderRadius: BorderRadius.sm, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.white, paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs, fontSize: FontSizes.base, color: Colors.gray[900] },
  manualGeocodeStatus: { minHeight: 20, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, paddingHorizontal: 2 },
  manualGeocodeStatusText: { fontSize: FontSizes.xs, fontWeight: FontWeights.semibold, color: Colors.primary },
  manualGeocodeStatusTextFound: { color: Colors.success },
  manualGeocodeStatusTextMissing: { color: Colors.danger },
  rideReferenceInput: { minHeight: 38, borderRadius: BorderRadius.sm, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs, fontSize: FontSizes.sm, color: Colors.gray[800] },
  rideDivider: { height: 1, backgroundColor: Colors.gray[200], marginVertical: Spacing.xs },
  quickActionsRow: { flexDirection: 'row', gap: Spacing.sm },
  quickActionButton: { flex: 1, minHeight: 42, borderRadius: BorderRadius.full, backgroundColor: `${Colors.primary}0F`, borderWidth: 1, borderColor: `${Colors.primary}22`, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, paddingHorizontal: Spacing.sm },
  quickActionText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.primary },
  suggestionsSection: { gap: Spacing.sm },
  suggestionsHeader: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  suggestionsTitle: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  suggestionsToggleButton: { minHeight: 40, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.sm },
  suggestionsToggle: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.primary },
  suggestionsScroll: { gap: Spacing.sm, paddingRight: Spacing.xl },
  suggestionChip: { maxWidth: 170, minHeight: 42, borderRadius: BorderRadius.full, backgroundColor: Colors.gray[50], borderWidth: 1, borderColor: Colors.gray[200], paddingLeft: 6, paddingRight: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  suggestionChipDisabled: { opacity: 0.48 },
  suggestionIcon: { width: 30, height: 30, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.white },
  suggestionText: { flexShrink: 1, fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[800] },
  requestStepper: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: BorderRadius.sm, padding: 6, gap: Spacing.xs },
  requestStepPill: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, minHeight: 36, borderRadius: BorderRadius.sm, paddingHorizontal: Spacing.sm, backgroundColor: Colors.gray[50] },
  requestStepPillActive: { backgroundColor: `${Colors.primary}10` },
  requestStepPillDisabled: { opacity: 0.5 },
  requestStepNumber: { width: 22, height: 22, borderRadius: BorderRadius.full, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray[200] },
  requestStepNumberActive: { backgroundColor: Colors.primary },
  requestStepNumberText: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[600] },
  requestStepNumberTextActive: { color: Colors.white },
  requestStepLabel: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[600] },
  requestStepLabelActive: { color: Colors.primary },
  requestStepLine: { flex: 1, height: 1, backgroundColor: Colors.gray[200] },
  requestStepLineActive: { backgroundColor: Colors.primary },
  hero: { borderRadius: BorderRadius.xxl, padding: Spacing.xl, gap: Spacing.sm },
  heroPill: { alignSelf: 'flex-start', paddingHorizontal: Spacing.md, paddingVertical: 6, borderRadius: BorderRadius.full, backgroundColor: 'rgba(255,255,255,0.16)', color: Colors.white, fontWeight: FontWeights.semibold },
  heroTitle: { fontSize: FontSizes.xxl, fontWeight: FontWeights.bold, color: Colors.white, lineHeight: 34 },
  heroSubtitle: { fontSize: FontSizes.base, color: 'rgba(255,255,255,0.92)', lineHeight: 22 },
  card: { backgroundColor: Colors.white, borderRadius: BorderRadius.sm, padding: Spacing.md, gap: Spacing.sm, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 2 },
  cardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: Spacing.md },
  cardHeadCompact: { backgroundColor: Colors.white, borderRadius: BorderRadius.sm, padding: Spacing.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTitle: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  cardSubtitle: { marginTop: 2, fontSize: 13, color: Colors.gray[500] },
  stepIntroCard: { backgroundColor: Colors.white, borderRadius: BorderRadius.sm, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  stepIntroIcon: { width: 30, height: 30, borderRadius: BorderRadius.sm, alignItems: 'center', justifyContent: 'center', backgroundColor: `${Colors.primary}12` },
  stepIntroText: { flex: 1 },
  stepIntroTitle: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  stepIntroSubtitle: { marginTop: 2, fontSize: FontSizes.sm, color: Colors.gray[500], lineHeight: 18 },
  stepBackButton: { minHeight: 34, borderRadius: BorderRadius.sm, borderWidth: 1, borderColor: Colors.gray[200], alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.sm },
  stepBackButtonText: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  iconCircle: { width: 40, height: 40, borderRadius: BorderRadius.full, backgroundColor: `${Colors.primary}12`, alignItems: 'center', justifyContent: 'center' },
  routeRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  routeDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: Colors.primary },
  squareDot: { borderRadius: 3 },
  routeText: { flex: 1 },
  routeLabel: { fontSize: FontSizes.xs, color: Colors.gray[500], textTransform: 'uppercase', fontWeight: FontWeights.bold, letterSpacing: 0.6 },
  routeValue: { marginTop: 4, fontSize: FontSizes.base, fontWeight: FontWeights.semibold, color: Colors.gray[900] },
  placeholder: { color: Colors.gray[400] },
  routeHint: { marginTop: 2, fontSize: FontSizes.sm, color: Colors.gray[500] },
  addressBlock: { gap: Spacing.sm },
  addressChoiceRow: { flexDirection: 'row', gap: Spacing.sm, marginLeft: 26 },
  addressChoiceButton: { flex: 1, minHeight: 66, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], padding: Spacing.sm, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  addressChoiceButtonActive: { borderColor: Colors.primary, backgroundColor: `${Colors.primary}10` },
  addressChoiceText: { flex: 1 },
  addressChoiceTitle: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  addressChoiceHint: { marginTop: 2, fontSize: FontSizes.xs, color: Colors.gray[500] },
  manualLocationGroup: { gap: Spacing.sm, marginLeft: 26 },
  manualLocationLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.gray[600] },
  manualLocationInput: { minHeight: 48, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, fontSize: FontSizes.base, color: Colors.gray[900] },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  chip: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, backgroundColor: Colors.gray[100], borderRadius: BorderRadius.full, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm },
  primaryChip: { backgroundColor: `${Colors.primary}12` },
  chipText: { fontSize: FontSizes.sm, fontWeight: FontWeights.medium, color: Colors.gray[800] },
  flexChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  flexChipTextActive: { color: Colors.white },
  detailsCard: { paddingBottom: Spacing.sm },
  presetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  preset: { minHeight: 42, flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.gray[50], borderRadius: BorderRadius.sm, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: Colors.gray[100], gap: 6 },
  presetActive: { backgroundColor: `${Colors.primary}10`, borderColor: Colors.primary },
  presetLabel: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[900] },
  presetLabelActive: { color: Colors.primary },
  presetCaption: { fontSize: FontSizes.xs, color: Colors.gray[500] },
  infoCard: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, backgroundColor: Colors.gray[50], borderRadius: BorderRadius.sm, padding: Spacing.sm },
  infoCardText: { flex: 1, fontSize: 13, color: Colors.gray[900], fontWeight: FontWeights.semibold, lineHeight: 18 },
  customWrap: { gap: Spacing.sm },
  inputLike: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, borderRadius: BorderRadius.sm, backgroundColor: Colors.gray[50], borderWidth: 1, borderColor: Colors.gray[100], padding: Spacing.sm },
  inputLikeText: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[900] },
  counter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.gray[50], borderRadius: BorderRadius.xl, padding: Spacing.md },
  counterBtn: { width: 48, height: 48, borderRadius: BorderRadius.lg, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center' },
  counterText: { alignItems: 'center', gap: 4 },
  counterValue: { fontSize: FontSizes.xxl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  counterLabel: { fontSize: FontSizes.sm, color: Colors.gray[500] },
  smallLabel: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[600] },
  detailsPanel: { backgroundColor: Colors.white, borderRadius: BorderRadius.sm, padding: Spacing.md, gap: Spacing.sm, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 2 },
  detailsFieldRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md },
  detailsFieldLabelBlock: { flex: 1, minWidth: 0 },
  detailsFieldTitle: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  detailsFieldHint: { marginTop: 2, fontSize: FontSizes.xs, color: Colors.gray[500] },
  detailsDivider: { height: 1, backgroundColor: Colors.gray[100] },
  counterCompact: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Colors.gray[50], borderRadius: BorderRadius.sm, padding: 4 },
  counterBtnCompact: { width: 34, height: 34, borderRadius: BorderRadius.sm, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center' },
  counterBtnCompactDisabled: { backgroundColor: Colors.gray[100] },
  counterValueCompact: { minWidth: 28, textAlign: 'center', fontSize: FontSizes.lg, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  priceBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.gray[50], borderRadius: BorderRadius.sm, paddingHorizontal: Spacing.lg, height: 52, borderWidth: 1, borderColor: Colors.gray[100] },
  priceInput: { flex: 1, fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  priceBoxCompact: { width: 150, height: 42, flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.gray[50], borderRadius: BorderRadius.sm, paddingHorizontal: Spacing.sm, borderWidth: 1, borderColor: Colors.gray[100] },
  priceInputCompact: { flex: 1, fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  currency: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[500] },
  textArea: { minHeight: 78, borderRadius: BorderRadius.sm, backgroundColor: Colors.gray[50], borderWidth: 1, borderColor: Colors.gray[100], padding: Spacing.md, fontSize: FontSizes.base, color: Colors.gray[900], textAlignVertical: 'top', lineHeight: 22 },
  summary: { backgroundColor: Colors.white, borderRadius: BorderRadius.sm, padding: Spacing.md, gap: 2 },
  summaryTitle: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  summaryText: { fontSize: 13, color: Colors.gray[600], lineHeight: 18 },
  footer: { backgroundColor: Colors.white, borderTopWidth: 1, borderTopColor: Colors.gray[100], paddingHorizontal: Spacing.lg, paddingTop: Spacing.xs, paddingBottom: Spacing.sm, shadowColor: '#0F172A', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 8 },
  footerCompact: { paddingTop: Spacing.sm },
  footerActionsRow: { marginTop: 0, flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  footerSecondaryButton: { minWidth: 108, minHeight: 52, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.md },
  footerSecondaryButtonText: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[700] },
  mainButtonWrap: { width: '100%' },
  mainButtonWrapCompact: { flex: 1, width: 'auto' },
  mainButton: { minHeight: 56, borderRadius: BorderRadius.lg, backgroundColor: Colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, marginTop: Spacing.sm, shadowColor: Colors.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.24, shadowRadius: 12, elevation: 5 },
  mainButtonCompact: { minHeight: 52, marginTop: 0 },
  mainButtonDisabled: { opacity: 0.65 },
  mainButtonText: { color: Colors.white, fontSize: FontSizes.base, fontWeight: FontWeights.bold },
  submissionErrorBanner: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.sm, padding: Spacing.sm, borderRadius: BorderRadius.sm, backgroundColor: Colors.danger + '10' },
  submissionErrorText: { flex: 1, fontSize: FontSizes.sm, lineHeight: 18, color: Colors.danger },
  requestSuccessOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.lg, backgroundColor: 'rgba(15, 23, 42, 0.82)' },
  requestSuccessBackdropGlowTop: { position: 'absolute', top: -92, right: -70, width: 230, height: 230, borderRadius: 115, backgroundColor: Colors.primary + '38' },
  requestSuccessBackdropGlowBottom: { position: 'absolute', left: -74, bottom: -90, width: 240, height: 240, borderRadius: 120, backgroundColor: Colors.success + '2E' },
  requestSuccessCard: { width: '100%', maxWidth: 430, alignItems: 'center', paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg, paddingBottom: Spacing.xl, borderRadius: 34, backgroundColor: Colors.white, borderWidth: 1, borderColor: 'rgba(255,255,255,0.72)', shadowColor: '#000', shadowOffset: { width: 0, height: 22 }, shadowOpacity: 0.24, shadowRadius: 34, elevation: 18 },
  requestSuccessPill: { alignSelf: 'center', minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: Spacing.md, borderRadius: BorderRadius.full, backgroundColor: Colors.primary + '10', borderWidth: 1, borderColor: Colors.primary + '18', marginBottom: Spacing.lg },
  requestSuccessPillText: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: Colors.primaryDark },
  requestSuccessIcon: { width: 84, height: 84, alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.lg, borderRadius: BorderRadius.full, backgroundColor: Colors.success, shadowColor: Colors.success, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.28, shadowRadius: 18, elevation: 8 },
  requestSuccessTitle: { fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900], textAlign: 'center' },
  requestSuccessText: { marginTop: Spacing.sm, marginBottom: Spacing.lg, fontSize: FontSizes.base, lineHeight: 23, color: Colors.gray[600], textAlign: 'center' },
  requestSuccessLoadingRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, paddingHorizontal: Spacing.md, borderRadius: BorderRadius.full, backgroundColor: Colors.primary + '0D' },
  requestSuccessLoadingText: { fontSize: FontSizes.sm, fontWeight: FontWeights.bold, color: Colors.primaryDark },
  requestSuccessActions: { width: '100%', gap: Spacing.sm },
  requestSuccessPrimary: { width: '100%', minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, borderRadius: BorderRadius.full, backgroundColor: Colors.primary },
  requestSuccessPrimaryText: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.white },
  requestSuccessSecondary: { width: '100%', minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50] },
  requestSuccessSecondaryText: { fontSize: FontSizes.base, fontWeight: FontWeights.semibold, color: Colors.gray[700] },
  iosOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.35)' },
  iosSheet: { backgroundColor: Colors.white, borderTopLeftRadius: BorderRadius.xl, borderTopRightRadius: BorderRadius.xl, paddingTop: Spacing.md },
  iosPicker: { height: 216 },
  iosDone: { padding: Spacing.lg, alignItems: 'center', borderTopWidth: 1, borderTopColor: Colors.gray[100] },
  iosDoneText: { color: Colors.primary, fontWeight: FontWeights.bold, fontSize: FontSizes.base },
});
