import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from '@/constants/styles';
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.gray[50] },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { minHeight: 64, paddingHorizontal: Spacing.lg, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: Colors.gray[100], backgroundColor: Colors.white },
  headerButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray[50] },
  headerText: { flex: 1, marginHorizontal: Spacing.md },
  headerTitle: { fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  headerSubtitle: { marginTop: 2, fontSize: FontSizes.xs, color: Colors.gray[500] },
  content: { padding: Spacing.lg, gap: Spacing.lg, paddingBottom: 44 },
  sectionStack: { gap: Spacing.lg },
  hero: { backgroundColor: Colors.primary, borderRadius: BorderRadius.xl, padding: Spacing.xl, overflow: 'hidden' },
  eyebrow: { color: '#FFE1D6', fontSize: FontSizes.xs, fontWeight: FontWeights.bold, letterSpacing: 1.4 },
  linkReady: { color: Colors.white, fontSize: FontSizes.xxl, fontWeight: FontWeights.bold, marginTop: 5 },
  heroText: { color: '#FFF4EF', fontSize: FontSizes.sm, lineHeight: 20, marginTop: Spacing.sm },
  heroActions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.lg },
  shareButton: { flex: 1, minHeight: 46, borderRadius: BorderRadius.md, backgroundColor: Colors.primaryDark, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
  earningSummary: { alignItems: 'flex-end', marginLeft: Spacing.sm },
  earningAmount: { marginTop: 3, fontSize: FontSizes.xs, color: Colors.gray[500] },
  pendingEarning: { marginTop: 3, fontSize: FontSizes.xs, color: Colors.warningDark },
  shareButtonText: { color: Colors.white, fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  contactsButton: { width: 48, borderRadius: BorderRadius.md, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center' },
  balancePanel: { backgroundColor: Colors.white, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], overflow: 'hidden' },
  balanceMain: { padding: Spacing.lg },
  balanceLabel: { color: Colors.gray[600], fontSize: FontSizes.sm, fontWeight: FontWeights.semibold },
  balanceValue: { color: Colors.gray[900], fontSize: FontSizes.xxxl, fontWeight: FontWeights.bold, marginTop: 4 },
  equivalent: { color: Colors.successDark, fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, marginTop: 3 },
  balanceStats: { minHeight: 72, flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.gray[50], borderTopWidth: 1, borderTopColor: Colors.gray[100] },
  stat: { flex: 1, alignItems: 'center', paddingHorizontal: 4 },
  statDivider: { height: 30, width: 1, backgroundColor: Colors.gray[200] },
  statValue: { color: Colors.gray[900], fontSize: FontSizes.base, fontWeight: FontWeights.bold },
  statLabel: { marginTop: 3, color: Colors.gray[500], fontSize: 11 },
  panel: { backgroundColor: Colors.white, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], padding: Spacing.lg, gap: Spacing.md },
  sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm },
  sectionTitle: { color: Colors.gray[900], fontSize: FontSizes.lg, fontWeight: FontWeights.bold },
  sectionHint: { color: Colors.gray[500], fontSize: FontSizes.xs, marginTop: 4, maxWidth: 230, lineHeight: 17 },
  kycBadge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.warning + '18', borderRadius: BorderRadius.full, paddingHorizontal: 9, paddingVertical: 6 },
  kycBadgeOk: { backgroundColor: Colors.success + '16' },
  kycText: { color: Colors.warningDark, fontSize: 11, fontWeight: FontWeights.bold },
  kycTextOk: { color: Colors.successDark },
  input: { height: 50, borderRadius: BorderRadius.md, borderWidth: 1, borderColor: Colors.gray[200], backgroundColor: Colors.gray[50], paddingHorizontal: Spacing.md, color: Colors.gray[900], fontSize: FontSizes.base },
  withdrawButton: { height: 50, borderRadius: BorderRadius.md, backgroundColor: Colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
  withdrawButtonText: { color: Colors.white, fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  legalHint: { color: Colors.gray[500], fontSize: 11, lineHeight: 16 },
  sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  counter: { color: Colors.primary, fontSize: FontSizes.sm, fontWeight: FontWeights.bold, backgroundColor: Colors.primary + '12', paddingHorizontal: 9, paddingVertical: 4, borderRadius: BorderRadius.full },
  listPanel: { backgroundColor: Colors.white, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: Colors.gray[200], overflow: 'hidden' },
  listItem: { minHeight: 68, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.gray[100] },
  listIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary + '10' },
  payoutIcon: { backgroundColor: Colors.info + '10' },
  listBody: { flex: 1, minWidth: 0 },
  listTitle: { color: Colors.gray[900], fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  listMeta: { color: Colors.gray[500], fontSize: 11, marginTop: 4 },
  positiveAmount: { color: Colors.successDark, fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  negativeAmount: { color: Colors.danger, fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  empty: { minHeight: 116, alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, padding: Spacing.lg },
  emptyText: { color: Colors.gray[500], fontSize: FontSizes.sm },
  disabled: { opacity: 0.6 },
});
