import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  driverDecisionGhostText: {
    color: Colors.primary,
    fontWeight: FontWeights.semibold,
    marginLeft: Spacing.xs,
  },
  editModalKeyboard: {
    flex: 1,
  },
  editModalKeyboardIos: {
    backgroundColor: Colors.white,
  },
  editModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  editModalOverlayIos: {
    backgroundColor: Colors.white,
    justifyContent: 'flex-start',
  },
  editModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  editModalSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '92%',
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.sm,
    flexDirection: 'column',
    elevation: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
  },
  editModalSheetIos: {
    flex: 1,
    maxHeight: '100%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: Spacing.lg,
    elevation: 0,
    shadowOpacity: 0,
  },
  editModalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.gray[300],
    marginTop: Spacing.xs,
    marginBottom: Spacing.lg,
  },
  editModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.xl,
  },
  editModalHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: Colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editModalTitle: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  editModalSubtitle: {
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
    marginTop: 2,
  },
  editModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.gray[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  editStepIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: 4,
    marginBottom: Spacing.lg,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.gray[50],
  },
  editStepPill: {
    flex: 1,
    minHeight: 34,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  editStepPillActive: {
    backgroundColor: Colors.white,
    borderColor: Colors.primary + '25',
  },
  editStepText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[500],
  },
  editStepTextActive: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  editModalScrollView: {
    minHeight: 220,
    maxHeight: 430,
  },
  editModalScrollViewIos: {
    flex: 1,
    maxHeight: '100%',
  },
  editModalScroll: {
    paddingBottom: Spacing.xl,
    flexGrow: 1,
  },
  editSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  editSectionIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: Colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editSectionTitle: {
    flex: 1,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: Colors.gray[800],
  },
  editVehicleState: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.gray[50],
  },
  editVehicleStateText: {
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
  },
  editVehicleList: {
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  editVehicleOption: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.white,
  },
  editVehicleOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '08',
  },
  editVehicleCopy: {
    flex: 1,
  },
  editVehicleName: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  editVehicleMeta: {
    marginTop: 2,
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
  },
  editSwapBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.primary + '12',
    borderWidth: 1,
    borderColor: Colors.primary + '18',
  },
  editSwapText: {
    fontSize: FontSizes.xs,
    color: Colors.primary,
    fontWeight: FontWeights.semibold,
  },
  editModeRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.sm,
    padding: 4,
    marginBottom: Spacing.md,
  },
  editModeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  editModeChipActive: {
    borderColor: Colors.primary + '30',
    backgroundColor: Colors.white,
  },
  editModeChipText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.medium,
    color: Colors.gray[500],
  },
  editModeChipTextActive: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  editRouteCard: {
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.white,
    overflow: 'hidden',
    marginBottom: Spacing.md,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  editRouteDividerLine: {
    height: 1,
    backgroundColor: Colors.gray[200],
    marginHorizontal: Spacing.md,
  },
  editRouteManualItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
    padding: Spacing.md,
    backgroundColor: Colors.white,
  },
  editRouteManualDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 14,
  },
  editRouteManualLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    color: Colors.gray[500],
    textTransform: 'uppercase',
    marginBottom: 4,
  }
});
