import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  tripInlineWhatsappText: {
    color: '#25D366',
  },
  mapModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
  },
  mapModalContent: {
    flex: 1,
    marginHorizontal: 16,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: Colors.white,
  },
  fullscreenMap: {
    width: '100%',
    height: '100%',
  },
  closeMapButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 48,
    height: 48,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    elevation: 20,
    borderWidth: 2,
    borderColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.24,
    shadowRadius: 8,
  },
  trackingBanner: {
    marginHorizontal: Spacing.lg,
    marginTop: 0,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    backgroundColor: Colors.info + '08',
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Colors.info + '20',
  },
  trackingBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: Spacing.md,
  },
  trackingStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: Spacing.md,
  },
  trackingStatusDotActive: {
    backgroundColor: Colors.success,
  },
  trackingStatusDotIdle: {
    backgroundColor: Colors.gray[400],
  },
  trackingTitle: {
    fontSize: 14,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  trackingSubtitle: {
    fontSize: 12,
    color: Colors.gray[600],
    marginTop: 2,
  },
  trackingRefreshButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.gray[200],
  },
  statusContainer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: 0,
    paddingBottom: Spacing.md,
  },
  statusCard: {
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray[100],
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  statusHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: Spacing.sm,
  },
  statusLabel: {
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    fontSize: 14,
  },
  progressText: {
    fontSize: 12,
    fontWeight: FontWeights.bold,
    color: Colors.gray[700],
  },
  progressBar: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: BorderRadius.full,
    overflow: 'hidden',
    marginBottom: Spacing.sm,
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors.info,
  },
  etaText: {
    fontSize: 12,
    color: Colors.gray[700],
    fontWeight: FontWeights.medium,
  },
  section: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  sectionCard: {
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: FontWeights.bold,
    color: Colors.gray[400],
    marginBottom: Spacing.lg,
    letterSpacing: 0,
  },
  tripSafetyPassengerCard: {
    padding: Spacing.sm,
    borderColor: Colors.primary + '20',
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  tripSafetyCompactSosButton: {
    width: 82,
    minHeight: 56,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tripSafetyCompactSosText: {
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    letterSpacing: 0.3,
  },
  tripSafetyCompactButtonBlurred: {
    opacity: 0.42,
  },
  tripSafetyCompactTextBlurred: {
    color: Colors.gray[400],
  },
  tripSafetyCompactTrustedButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '28',
    backgroundColor: Colors.primary + '07',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  tripSafetyCompactTrustedDisabled: {
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[100],
  },
  tripSafetyCompactTrustedIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '18',
  },
  tripSafetyCompactTrustedCopy: {
    flex: 1,
    minWidth: 0,
  },
  tripSafetyCompactTrustedTitle: {
    fontSize: 13,
    color: Colors.gray[900],
    fontWeight: FontWeights.bold,
  },
  tripSafetyCompactTrustedSubtitle: {
    marginTop: 2,
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
  },
  tripSafetyCard: {
    borderColor: Colors.primary + '30',
    backgroundColor: Colors.white,
    gap: Spacing.md,
  },
  tripSafetyHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  tripSafetyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary + '12',
    borderWidth: 1,
    borderColor: Colors.primary + '24',
  },
  tripSafetyHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  tripSafetyTitle: {
    fontSize: FontSizes.base,
    color: Colors.gray[900],
    fontWeight: FontWeights.bold,
  },
  tripSafetySubtitle: {
    marginTop: 2,
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
    lineHeight: 19,
  },
  tripSafetyNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    borderWidth: 1,
    borderColor: Colors.primary + '20',
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary + '08',
    padding: Spacing.sm,
  },
  tripSafetyNoticeText: {
    flex: 1,
    fontSize: FontSizes.xs,
    color: Colors.gray[700],
    lineHeight: 17,
  },
  tripSafetyActions: {
    gap: Spacing.sm,
  }
});
