import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  tripSheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[200],
    marginBottom: Spacing.md,
  },
  tripHeroSummary: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  tripHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
  },
  tripHeroTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  tripHeroStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  tripHeroStatusDot: {
    width: 9,
    height: 9,
    borderRadius: BorderRadius.full,
  },
  tripHeroEyebrow: {
    color: Colors.gray[500],
    fontSize: 11,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  tripHeroTitle: {
    color: Colors.gray[900],
    fontSize: 21,
    lineHeight: 25,
    fontWeight: FontWeights.bold,
  },
  tripPriceBadge: {
    minWidth: 86,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    backgroundColor: Colors.gray[900],
  },
  tripPriceBadgeText: {
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  tripPriceBadgeHint: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.68)',
    fontSize: 10,
    fontWeight: FontWeights.medium,
  },
  tripQuickFacts: {
    marginTop: Spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  tripQuickFact: {
    width: '48%',
    minHeight: 48,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  tripQuickFactIcon: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tripQuickFactLabel: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  tripQuickFactValue: {
    marginTop: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  tripInlineProgress: {
    marginTop: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.info + '08',
    borderWidth: 1,
    borderColor: Colors.info + '18',
    padding: Spacing.sm,
  },
  tripInlineProgressTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.xs,
  },
  tripInlineProgressLabel: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  tripInlineProgressValue: {
    color: Colors.info,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  tripInlineProgressTrack: {
    height: 5,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    overflow: 'hidden',
  },
  tripInlineProgressFill: {
    height: '100%',
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.info,
  },
  tripInlineProgressEta: {
    marginTop: Spacing.xs,
    color: Colors.gray[600],
    fontSize: 11,
    fontWeight: FontWeights.medium,
  },
  tripCompactRoute: {
    marginTop: Spacing.sm,
    flexDirection: 'row',
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.white,
    padding: Spacing.sm,
  },
  tripCompactRail: {
    width: 28,
    alignItems: 'center',
    paddingTop: 4,
  },
  tripCompactDot: {
    width: 12,
    height: 12,
    borderRadius: BorderRadius.full,
    borderWidth: 3,
    borderColor: Colors.white,
  },
  tripCompactStartDot: {
    backgroundColor: Colors.success,
  },
  tripCompactEndDot: {
    backgroundColor: Colors.primary,
  },
  tripCompactLine: {
    width: 2,
    flex: 1,
    minHeight: 34,
    marginVertical: 3,
    backgroundColor: Colors.gray[300],
  },
  tripCompactRouteCopy: {
    flex: 1,
    gap: Spacing.sm,
  },
  tripCompactStop: {
    minWidth: 0,
  },
  tripCompactStopTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  tripCompactStopLabel: {
    fontSize: 10,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  tripCompactDepartureLabel: {
    color: Colors.successDark,
  },
  tripCompactArrivalLabel: {
    color: Colors.primaryDark,
  },
  tripCompactStopTime: {
    color: Colors.gray[800],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  tripCompactStopName: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  tripCompactStopAddress: {
    marginTop: 1,
    color: Colors.gray[500],
    fontSize: 11,
    lineHeight: 15,
  },
  tripDirectInfoRow: {
    marginTop: Spacing.sm,
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  tripDriverCompact: {
    flex: 1,
    minHeight: 64,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.white,
    padding: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  tripDriverCompactAvatar: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  tripDriverCompactCopy: {
    flex: 1,
    minWidth: 0,
  },
  tripDriverCompactLabel: {
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  tripDriverCompactName: {
    marginTop: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  tripDriverCompactMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 1,
  },
  tripDriverCompactRating: {
    color: Colors.gray[700],
    fontSize: 11,
    fontWeight: FontWeights.bold,
  },
  tripVehicleCompact: {
    flex: 1,
    minHeight: 64,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.white,
    padding: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  tripVehicleCompactIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  }
});
