import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  tripVehicleCompactCopy: {
    flex: 1,
    minWidth: 0,
  },
  tripVehicleCompactName: {
    marginTop: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  tripVehicleCompactMeta: {
    marginTop: 1,
    color: Colors.gray[600],
    fontSize: 11,
    fontWeight: FontWeights.medium,
  },
  vehicleDetailModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  vehicleDetailModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 15, 15, 0.55)',
  },
  vehicleDetailModalCard: {
    width: '100%',
    maxHeight: '88%',
    overflow: 'hidden',
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 16,
  },
  vehicleDetailModalHeader: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  vehicleDetailModalPhoto: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: Colors.gray[100],
  },
  vehicleDetailModalBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleDetailModalHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  vehicleDetailModalCloseIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.gray[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleDetailModalBody: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    gap: Spacing.md,
  },
  vehicleDetailModalChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  vehicleDetailModalChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
  },
  vehicleDetailModalChipSuccess: {
    backgroundColor: Colors.success + '14',
  },
  vehicleDetailModalChipMuted: {
    backgroundColor: Colors.gray[100],
  },
  vehicleDetailModalChipText: {
    color: Colors.gray[700],
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  vehicleDetailModalChipTextSuccess: {
    color: Colors.successDark,
  },
  vehicleDetailModalChipTextMuted: {
    color: Colors.gray[600],
  },
  vehicleDetailModalTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  vehicleDetailModalSubtitle: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  vehicleDetailModalPlate: {
    alignSelf: 'flex-start',
    minWidth: 148,
    borderRadius: BorderRadius.md,
    borderWidth: 2,
    borderColor: Colors.gray[900],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  vehicleDetailModalPlateCaption: {
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: FontWeights.bold,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  vehicleDetailModalPlateValue: {
    marginTop: 2,
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  vehicleDetailModalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  vehicleDetailModalFact: {
    width: '48%',
    flexGrow: 1,
    flexBasis: '46%',
    minHeight: 64,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  vehicleDetailModalFactWide: {
    width: '100%',
    flexBasis: '100%',
  },
  vehicleDetailModalFactIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleDetailModalFactCopy: {
    flex: 1,
    minWidth: 0,
  },
  vehicleDetailModalFactLabel: {
    color: Colors.gray[500],
    fontSize: 11,
    fontWeight: FontWeights.bold,
    textTransform: 'uppercase',
  },
  vehicleDetailModalFactValue: {
    marginTop: 2,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  vehicleDetailModalSafetyNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary + '08',
    borderWidth: 1,
    borderColor: Colors.primary + '20',
  },
  vehicleDetailModalSafetyIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleDetailModalSafetyText: {
    flex: 1,
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    lineHeight: 20,
  },
  vehicleDetailModalCloseButton: {
    minHeight: 50,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleDetailModalCloseText: {
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  passengerKycTripNotice: {
    marginTop: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primary + '08',
  },
  passengerKycTripNoticeIcon: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  passengerKycTripNoticeCopy: {
    flex: 1,
    minWidth: 0,
  },
  passengerKycTripNoticeTitle: {
    color: Colors.gray[700],
    fontSize: FontSizes.xs,
    lineHeight: 18,
    fontWeight: FontWeights.semibold,
  },
  passengerKycTripNoticeText: {
    marginTop: 3,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  tripInlineActions: {
    marginTop: Spacing.sm,
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  tripInlineActionButton: {
    flex: 1,
    minHeight: 44,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.xs,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
  },
  tripInlineActionButtonDisabled: {
    backgroundColor: Colors.gray[50],
  },
  tripInlineActionText: {
    flexShrink: 1,
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  }
});
