import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/styles';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.white },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14, gap: 12 },
  heading: { flex: 1 },
  title: { fontSize: 21, fontWeight: '700', color: Colors.gray[900] },
  subtitle: { fontSize: 13, color: Colors.gray[600], marginTop: 4 },
  iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray[50] },
  search: { marginHorizontal: 20, minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 10, paddingLeft: 14, paddingRight: 4, borderRadius: 14, backgroundColor: Colors.gray[100], borderWidth: 1, borderColor: Colors.gray[100] },
  searchFocused: { borderColor: Colors.primary, backgroundColor: Colors.white },
  input: { flex: 1, paddingVertical: 12, fontSize: 15, color: Colors.gray[900], minWidth: 0 },
  clearButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  shortcuts: { flexDirection: 'row', alignItems: 'center', paddingLeft: 20, paddingVertical: 8, gap: 10 },
  shortcut: { flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 44, paddingHorizontal: 10, borderRadius: 12 },
  shortcutSelected: { backgroundColor: '#FFF1EB' },
  shortcutText: { fontSize: 13, fontWeight: '600', color: Colors.primaryDark },
  shortcutDivider: { height: 18, width: 1, backgroundColor: Colors.gray[200] },
  landmarks: { alignItems: 'center', paddingRight: 20, gap: 8 },
  landmark: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, backgroundColor: Colors.gray[50], borderRadius: 12 },
  landmarkText: { fontSize: 13, color: Colors.gray[700], maxWidth: 150 },
  shortcutsHint: { fontSize: 12, color: Colors.gray[600] },
  workspace: { flex: 1, minHeight: 90, overflow: 'hidden', position: 'relative' },
  locate: { position: 'absolute', bottom: 16, right: 16, minHeight: 48, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 24, backgroundColor: Colors.white, elevation: 2, shadowColor: Colors.black, shadowOffset: { width: 0, height: 2 }, shadowRadius: 4, shadowOpacity: 0.08 },
  locateText: { fontSize: 13, color: Colors.gray[800], fontWeight: '600' },
  results: { position: 'absolute', top: 0, left: 0, right: 0, maxHeight: '100%', backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.gray[200] },
  resultsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 },
  resultsHeading: { fontSize: 13, color: Colors.gray[600], fontWeight: '600', flex: 1 },
  resultRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, paddingHorizontal: 20, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.gray[200], minHeight: 64 },
  resultCopy: { flex: 1 },
  resultTitle: { fontSize: 15, color: Colors.gray[900], fontWeight: '600' },
  resultAddress: { fontSize: 12, color: Colors.gray[600], marginTop: 3 },
  resultArrow: { transform: [{ rotate: '45deg' }] },
  empty: { color: Colors.gray[600], fontSize: 14, lineHeight: 20, padding: 20 },
  footer: { paddingHorizontal: 20, paddingTop: 14, borderTopWidth: 1, borderTopColor: Colors.gray[100], backgroundColor: Colors.white },
  notice: { fontSize: 13, lineHeight: 18, color: Colors.gray[700], paddingBottom: 10 },
  selection: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 },
  selectionIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFF1EB', alignItems: 'center', justifyContent: 'center' },
  selectionCopy: { flex: 1, minWidth: 0 },
  selectionLabel: { fontSize: 10, letterSpacing: 0.8, fontWeight: '600', color: Colors.gray[600] },
  selectionTitle: { fontSize: 16, fontWeight: '700', color: Colors.gray[900], marginTop: 3 },
  selectionAddress: { fontSize: 12, color: Colors.gray[600], marginTop: 3 },
  confirm: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, padding: 14, borderRadius: 14, backgroundColor: Colors.primary },
  confirmDisabled: { backgroundColor: Colors.gray[400] },
  confirmText: { color: Colors.white, fontSize: 16, fontWeight: '700' },
});
