import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from '@/constants/styles';

export const passengerPanelStyles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)' },
  sheet: { maxHeight: '85%', backgroundColor: Colors.white, paddingTop: Spacing.md,
    borderTopLeftRadius: BorderRadius.xxl, borderTopRightRadius: BorderRadius.xxl },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Colors.gray[300],
    alignSelf: 'center', marginBottom: Spacing.lg },
  list: { flexGrow: 0, flexShrink: 1 },
  listContent: { paddingHorizontal: Spacing.lg },
  header: { paddingBottom: Spacing.md, gap: Spacing.sm },
  title: { fontSize: FontSizes.xl, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  subtitle: { fontSize: FontSizes.sm, color: Colors.gray[600] },
  summary: { flexDirection: 'row', paddingVertical: Spacing.md, backgroundColor: Colors.gray[50], borderRadius: BorderRadius.md },
  summaryItem: { flex: 1, minWidth: 0, alignItems: 'center', paddingHorizontal: Spacing.xs, gap: 2 },
  summaryValue: { fontSize: FontSizes.lg, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  summaryLabel: { fontSize: FontSizes.xs, color: Colors.gray[700], textAlign: 'center' },
  hint: { fontSize: FontSizes.xs, lineHeight: 18, color: Colors.gray[600] },
  row: { padding: Spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.gray[200], gap: Spacing.xs },
  nextRow: { backgroundColor: '#FFF5EE', borderRadius: BorderRadius.md, borderBottomWidth: 0,
    borderLeftWidth: 3, borderLeftColor: Colors.primary, marginBottom: Spacing.sm },
  nextLabel: { fontSize: FontSizes.xs, fontWeight: FontWeights.bold, color: '#9A3412', marginBottom: 2 },
  name: { fontSize: FontSizes.base, fontWeight: FontWeights.bold, color: Colors.gray[900] },
  status: { fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[700] },
  locationLabel: { fontSize: FontSizes.xs, color: Colors.gray[600], marginTop: Spacing.xs },
  address: { fontSize: FontSizes.sm, color: Colors.gray[900] },
  actions: { flexDirection: 'row', flexWrap: 'wrap', columnGap: Spacing.lg, marginTop: Spacing.xs },
  detailButton: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, minHeight: 44, flexShrink: 1 },
  detailText: { flexShrink: 1, fontSize: FontSizes.sm, fontWeight: FontWeights.semibold, color: Colors.gray[900] },
  reportButton: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, minHeight: 44, flexShrink: 1 },
  reportText: { flexShrink: 1, fontSize: FontSizes.xs, color: Colors.gray[700] },
  footer: { paddingTop: Spacing.md, paddingHorizontal: Spacing.lg },
  closeButton: { minHeight: 48, paddingVertical: Spacing.md, paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md, backgroundColor: Colors.gray[900], alignItems: 'center' },
  closeText: { color: Colors.white, fontSize: FontSizes.base, fontWeight: FontWeights.semibold },
  empty: { paddingVertical: Spacing.xl, fontSize: FontSizes.sm, color: Colors.gray[600], textAlign: 'center' },
});
