import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  addressFieldArrivalReady: {
    borderColor: Colors.primary + '35',
    backgroundColor: Colors.primary + '06',
  },
  addressFieldLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    color: Colors.gray[500],
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  addressFieldLabelReady: {
    color: Colors.gray[800],
  },
  addressInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  addressInputButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    minHeight: 44,
    borderWidth: 0,
    borderColor: 'transparent',
    borderRadius: BorderRadius.md,
    paddingHorizontal: 0,
    paddingVertical: Spacing.xs,
    backgroundColor: 'transparent',
  },
  addressInputButtonDepartureActive: {
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  addressInputButtonArrivalActive: {
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  addressInputText: {
    flex: 1,
    fontSize: FontSizes.base,
    color: Colors.gray[700],
    fontWeight: FontWeights.medium,
  },
  addressInputTextActive: {
    color: Colors.gray[900],
    fontWeight: FontWeights.bold,
  },
  modeToggle: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeToggleActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '10',
  },
  inlineManualInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    fontSize: FontSizes.base,
    color: Colors.gray[900],
    backgroundColor: Colors.gray[50],
    marginTop: Spacing.xs,
  },
  manualGeocodeStatus: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginTop: 2,
    paddingHorizontal: 2,
  },
  manualGeocodeStatusText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    color: Colors.primary,
  },
  manualGeocodeStatusTextFound: {
    color: Colors.success,
  },
  manualGeocodeStatusTextMissing: {
    color: Colors.danger,
  },
  gpsStatus: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: 2,
  },
  gpsStatusText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    color: Colors.warningDark,
  },
  gpsStatusTextReady: {
    color: Colors.success,
  },
  referenceField: {
    gap: Spacing.xs,
  },
  referenceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  referenceLabel: {
    fontSize: 11,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[600],
  },
  referenceInput: {
    minHeight: 38,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    fontSize: FontSizes.sm,
    color: Colors.gray[800],
    backgroundColor: Colors.gray[50],
  },
  referenceAddButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: 2,
  },
  referenceAddText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[600],
  },
  swapButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    marginVertical: -1,
  },
  swapButtonInner: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLandmarksSection: {
    marginBottom: 0,
    backgroundColor: 'transparent',
    borderRadius: BorderRadius.sm,
    borderWidth: 0,
    borderColor: 'transparent',
    paddingVertical: 0,
  },
  quickLandmarksOpenButton: {
    alignSelf: 'flex-start',
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '08',
    borderWidth: 1,
    borderColor: Colors.primary + '14',
  },
  quickLandmarksOpenText: {
    color: Colors.primaryDark,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  quickLandmarksHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  quickLandmarksTitle: {
    flex: 1,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[700],
  },
  quickLandmarksToggle: {
    padding: Spacing.xs,
  },
  quickLandmarksScroll: {
    gap: Spacing.sm,
    paddingLeft: Spacing.md,
    paddingRight: Spacing.xl,
  },
  quickLandmarkChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
  },
  quickLandmarkText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium,
    color: Colors.gray[700],
    maxWidth: 120,
  },
  inlineKycBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colors.primary + '08',
    borderRadius: BorderRadius.xl,
    borderWidth: 1.5,
    borderColor: Colors.primary + '20',
    padding: Spacing.md,
    marginBottom: 0,
  },
  inlineKycTitle: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    color: Colors.primary,
  },
  inlineKycSubtitle: {
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
    marginTop: 2,
  },
  fixedBottomBar: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 8,
  },
  fixedBottomBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  fixedFooterBackButton: {
    minWidth: 108,
    paddingVertical: Spacing.md,
    shadowOpacity: 0,
    elevation: 0,
  },
  fixedFooterPrimaryButton: {
    flex: 1,
    paddingVertical: Spacing.md,
  },
  fixedButton: {
    shadowColor: Colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 6,
  }
});
