import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  kycModalBadge: {
    width: 64,
    height: 64,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.sm,
  },
  kycModalTitle: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    textAlign: 'center',
  },
  kycModalSubtitle: {
    color: Colors.gray[600],
    fontSize: FontSizes.base,
    textAlign: 'center',
  },
  kycModalHighlights: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  kycHighlight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.gray[100],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
  },
  kycHighlightText: {
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium,
  },
  kycChecklist: {
    borderWidth: 1,
    borderColor: Colors.gray[100],
    borderRadius: BorderRadius.xl,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  kycChecklistItem: {
    flexDirection: 'row',
    gap: Spacing.md,
    alignItems: 'center',
    paddingVertical: Spacing.xs,
  },
  kycChecklistIcon: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kycChecklistContent: {
    flex: 1,
  },
  kycChecklistTitle: {
    fontWeight: FontWeights.semibold,
    color: Colors.gray[800],
  },
  kycChecklistSubtitle: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
  },
  kycModalActions: {
    gap: Spacing.sm,
  },
  kycPrimaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.primary,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.full,
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  kycPrimaryButtonDisabled: {
    opacity: 0.7,
  },
  kycPrimaryButtonText: {
    color: Colors.white,
    fontWeight: FontWeights.bold,
    fontSize: FontSizes.base,
  },
  kycSecondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[100],
    borderWidth: 1,
    borderColor: Colors.gray[200],
  },
  kycSecondaryButtonText: {
    color: Colors.gray[700],
    fontWeight: FontWeights.semibold,
  },
  // Driver Required Modal Styles
  driverModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  driverModalCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xl,
    alignItems: 'center',
    gap: Spacing.md,
    shadowColor: Colors.black,
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  driverModalIcon: {
    width: 80,
    height: 80,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverModalTitle: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    textAlign: 'center',
  },
  driverModalMessage: {
    fontSize: FontSizes.base,
    color: Colors.gray[600],
    textAlign: 'center',
    lineHeight: 22,
  },
  driverModalButtons: {
    flexDirection: 'row',
    gap: Spacing.md,
    width: '100%',
    marginTop: Spacing.md,
  },
  driverModalButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xl,
    alignItems: 'center',
  },
  driverModalButtonPrimary: {
    backgroundColor: Colors.primary,
  },
  driverModalButtonSecondary: {
    backgroundColor: Colors.gray[200],
  },
  driverModalButtonPrimaryText: {
    color: Colors.white,
    fontWeight: FontWeights.semibold,
  },
  driverModalButtonSecondaryText: {
    color: Colors.gray[700],
    fontWeight: FontWeights.semibold,
  },
  // Vehicle Selection Styles
  vehicleLoadingState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    gap: Spacing.md,
    minHeight: 200,
  },
  vehicleLoadingText: {
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
    textAlign: 'center',
    marginTop: Spacing.sm,
  },
  vehicleDefaultHint: {
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
    marginBottom: Spacing.sm,
  },
  vehicleSuccessBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: 'rgba(46, 204, 113, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(46, 204, 113, 0.28)',
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  vehicleSuccessIcon: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.success,
  },
  vehicleSuccessContent: {
    flex: 1,
    minWidth: 0,
  },
  vehicleSuccessTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    marginBottom: 2,
  },
  vehicleSuccessText: {
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 18,
  },
  vehicleEmptyState: {
    alignItems: 'center',
    padding: Spacing.xl,
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    gap: Spacing.md,
  },
  vehicleEmptyTitle: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold,
    color: Colors.gray[700],
  },
  vehicleEmptyText: {
    fontSize: FontSizes.sm,
    color: Colors.gray[500],
    textAlign: 'center',
  },
  addVehicleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    marginTop: Spacing.sm,
  },
  addVehicleButtonText: {
    color: Colors.white,
    fontWeight: FontWeights.semibold,
  },
  vehicleScrollView: {
    marginVertical: Spacing.sm,
  },
  vehicleScrollContent: {
    gap: Spacing.md,
    paddingRight: Spacing.md,
  },
  vehicleCard: {
    width: 178,
    minHeight: 158,
    padding: Spacing.md,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: BorderRadius.xl,
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  }
});
