import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  publishMapPreviewShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 78,
    backgroundColor: 'rgba(238,242,246,0.72)',
  },
  routeStatusBadge: {
    position: 'absolute',
    left: Spacing.lg,
    top: Spacing.md,
    minHeight: 38,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.white,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  routeStatusText: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    color: Colors.gray[800],
  },
  publishRouteSheet: {
    marginHorizontal: 0,
    marginTop: 0,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.white,
    padding: Spacing.lg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  rideSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  routeSheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  routeSheetSubtitle: {
    marginTop: 2,
    fontSize: FontSizes.sm,
    color: Colors.gray[500],
  },
  sectionTitle: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
    marginBottom: 0,
  },
  routeCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    padding: 0,
    flexDirection: 'row',
    borderWidth: 0,
    borderColor: 'transparent',
    marginBottom: 0,
  },
  routeVisual: {
    width: 24,
    alignItems: 'center',
    paddingTop: 22,
    paddingBottom: 22,
  },
  dotGreen: {
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: Colors.success,
    borderWidth: 3,
    borderColor: Colors.success + '20',
  },
  dotBlue: {
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: Colors.primary,
    borderWidth: 3,
    borderColor: Colors.primary + '20',
  },
  routeLine: {
    flex: 1,
    width: 3,
    backgroundColor: Colors.gray[200],
    marginVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
  },
  routeInputs: {
    flex: 1,
    marginLeft: Spacing.md,
    gap: Spacing.sm,
  },
  addressBlock: {
    gap: Spacing.sm,
  },
  addressMethodText: {
    fontSize: FontSizes.sm,
    color: Colors.gray[500],
    lineHeight: 18,
  },
  addressChoiceRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  addressChoiceButton: {
    flex: 1,
    minHeight: 66,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    padding: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  addressChoiceButtonActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '10',
  },
  addressChoiceText: {
    flex: 1,
  },
  addressChoiceTitle: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  addressChoiceHint: {
    marginTop: 2,
    fontSize: FontSizes.xs,
    color: Colors.gray[500],
  },
  locationSelector: {
    paddingVertical: Spacing.xs,
  },
  locationLabel: {
    fontSize: 10,
    fontWeight: FontWeights.bold,
    color: Colors.gray[400],
    letterSpacing: 0,
  },
  locationValue: {
    fontSize: FontSizes.base,
    color: Colors.gray[900],
    fontWeight: FontWeights.medium,
    marginTop: 4,
  },
  manualLocationLabel: {
    marginTop: Spacing.sm,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
    color: Colors.gray[600],
  },
  manualLocationInput: {
    minHeight: 46,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    marginTop: Spacing.sm,
    fontSize: FontSizes.base,
    color: Colors.gray[900],
  },
  infoBox: {
    flexDirection: 'row',
    backgroundColor: Colors.gray[50],
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[100],
    marginBottom: 0,
    alignItems: 'center',
  },
  infoText: {
    flex: 1,
    marginLeft: Spacing.sm,
    fontSize: FontSizes.sm,
    color: Colors.gray[600],
    lineHeight: 18,
  },
  // Card Styles (from request.tsx)
  card: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 1,
  },
  cardLabel: {
    fontSize: 10,
    fontWeight: FontWeights.bold,
    color: Colors.gray[400],
    letterSpacing: 0,
    marginBottom: Spacing.md,
  },
  row: {
    flexDirection: 'row',
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    padding: Spacing.xs,
  },
  counterBtn: {
    width: 36,
    height: 36,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  counterValue: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  priceInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    height: 48,
    gap: Spacing.md,
  },
  priceInput: {
    flex: 1,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    color: Colors.gray[900],
  },
  textAreaCard: {
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    fontSize: FontSizes.base,
    color: Colors.gray[900],
    minHeight: 80,
    textAlignVertical: 'top',
  },
  // === NOUVEAUX STYLES UX ROUTE ===
  addressField: {
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.gray[50],
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
  },
  addressFieldDepartureReady: {
    borderColor: Colors.success + '40',
    backgroundColor: Colors.success + '06',
  }
});
