import { BorderRadius, Colors, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.gray[50],
  },
  scrollRoot: {
    flex: 1,
  },
  header: {
    minHeight: 68,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.lg,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[200],
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
  },
  headerSubtitle: {
    marginTop: 2,
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
  },
  content: {
    padding: Spacing.xl,
    gap: Spacing.lg,
  },
  balancePanel: {
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary + '22',
    padding: Spacing.lg,
    gap: Spacing.sm,
  },
  balanceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  balanceIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceLabel: {
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  balanceLoader: {
    alignSelf: 'flex-start',
    marginVertical: Spacing.sm,
  },
  balanceValue: {
    color: Colors.gray[900],
    fontSize: FontSizes.xxxl,
    fontWeight: FontWeights.bold,
  },
  balanceHint: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    lineHeight: 20,
  },
  referralBanner: {
    minHeight: 76,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.primary + '24',
    backgroundColor: Colors.white,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  referralBannerIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colors.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  referralBannerText: { flex: 1, minWidth: 0 },
  referralBannerTitle: { color: Colors.gray[900], fontSize: FontSizes.sm, fontWeight: FontWeights.bold },
  referralBannerHint: { color: Colors.gray[500], fontSize: FontSizes.xs, lineHeight: 17, marginTop: 3 },
  actionRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  actionCard: {
    flex: 1,
    minHeight: 118,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  actionCardIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionCardIconSecondary: {
    backgroundColor: Colors.primary + '12',
  },
  actionCardTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  actionCardHint: {
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  followUpBanner: {
    minHeight: 72,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    backgroundColor: Colors.white,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  followUpIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  followUpCopy: {
    flex: 1,
    minWidth: 0,
  },
  followUpTitle: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  followUpText: {
    marginTop: 3,
    color: Colors.gray[600],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  sheetHost: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    elevation: 24,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  sheetKeyboard: {
    flex: 1,
    minHeight: 0,
    width: '100%',
  },
  sheetViewport: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'flex-end',
  },
  sheetCard: {
    width: '100%',
    minHeight: 0,
    maxHeight: '100%',
    flexShrink: 1,
    overflow: 'hidden',
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    shadowColor: Colors.black,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -5 },
    elevation: 16,
  },
  sheetHeader: {
    minHeight: 76,
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  sheetBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  sheetSubtitle: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
    lineHeight: 17,
  },
  sheetCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.gray[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetContent: {
    flexGrow: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    gap: Spacing.md,
  },
  sectionTitle: {
    color: Colors.gray[900],
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  methodRow: {
    gap: Spacing.sm,
  },
  methodButton: {
    minHeight: 58,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  methodButtonActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '08',
  },
  methodTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  methodLabel: {
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
  },
  methodHint: {
    marginTop: 2,
    color: Colors.gray[500],
    fontSize: FontSizes.xs,
  }
});
