import { BorderRadius, Colors, CommonStyles, FontSizes, FontWeights, Spacing } from "@/constants/styles";
import { SEARCH_COLORS } from "@/features/search/searchTheme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.gray[50],
  },
  header: {
    minHeight: 58,
    paddingHorizontal: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: SEARCH_COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray[50],
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.xs,
  },
  headerTitle: {
    flex: 1,
    color: Colors.primaryDark,
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.bold,
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '14',
  },
  headerAvatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarText: {
    color: Colors.primary,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xxl,
  },
  searchModeSegment: {
    marginTop: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.gray[200],
    padding: 2,
    flexDirection: 'row',
    gap: 4,
  },
  searchModeButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  searchModeButtonActive: {
    backgroundColor: Colors.primaryDark,
    ...CommonStyles.shadowSm,
  },
  searchModeButtonText: {
    color: Colors.gray[700],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
  },
  searchModeButtonTextActive: {
    color: Colors.white,
    fontWeight: FontWeights.bold,
  },
  routeSummaryCard: {
    minHeight: 96,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: SEARCH_COLORS.border,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    ...CommonStyles.shadowSm,
  },
  routeSummaryPlaces: {
    flex: 1,
    minWidth: 0,
    paddingRight: Spacing.sm,
  },
  routeSummaryRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  routeInputDivider: {
    height: 1,
    marginLeft: 22,
    backgroundColor: Colors.gray[100],
  },
  routeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  routeDotStart: {
    backgroundColor: Colors.successDark,
  },
  routeDotEnd: {
    backgroundColor: Colors.primaryDark,
  },
  routeInput: {
    flex: 1,
    color: Colors.gray[900],
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.bold,
    minHeight: 44,
    minWidth: 0,
    paddingVertical: 0,
  },
  clearRouteButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passengerBlock: {
    width: 96,
    minHeight: 58,
    borderLeftWidth: 1,
    borderLeftColor: SEARCH_COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passengerStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  passengerStepButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary + '12',
  },
  passengerStepButtonDisabled: {
    backgroundColor: Colors.gray[100],
  },
  passengerCountBlock: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
    alignItems: 'center',
  },
  passengerCount: {
    color: Colors.primaryDark,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
    lineHeight: 24,
  },
  passengerLabel: {
    color: SEARCH_COLORS.body,
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.bold,
  },
  loaderCard: {
    minHeight: 220,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: SEARCH_COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
    gap: Spacing.sm,
    ...CommonStyles.shadowSm,
  },
  loaderTitle: {
    color: SEARCH_COLORS.ink,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  loaderText: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    textAlign: 'center',
  },
  errorCard: {
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.dangerLight,
    padding: Spacing.xl,
    alignItems: 'center',
    gap: Spacing.sm,
  },
  errorText: {
    color: Colors.gray[800],
    fontSize: FontSizes.sm,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary + '14',
  },
  retryText: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  emptyCard: {
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: SEARCH_COLORS.border,
    padding: Spacing.xxl,
    alignItems: 'center',
    gap: Spacing.sm,
  },
  emptyIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: Colors.primary + '14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: SEARCH_COLORS.ink,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold,
  },
  emptyText: {
    color: Colors.gray[600],
    fontSize: FontSizes.sm,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyActionButton: {
    marginTop: Spacing.md,
    minHeight: 48,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  emptyActionText: {
    color: Colors.white,
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
  },
  resultSeparator: {
    height: Spacing.sm,
  }
});
